//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Alias.java
//

#ifndef Alias_H
#define Alias_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol SquiDBAlias < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface SquiDBAlias : NSObject < SquiDBAlias > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(SquiDBAlias)

FOUNDATION_EXPORT id<SquiDBAlias> create_SquiDBAlias(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBAlias)

#define ComYahooSquidbAnnotationsAlias SquiDBAlias


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // Alias_H
