//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CloseGuard.java
//

#ifndef CloseGuard_H
#define CloseGuard_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class JavaLangThrowable;
@protocol SquiDBCloseGuard_Reporter;

@interface SquiDBCloseGuard : NSObject

#pragma mark Public

- (void)close;

+ (SquiDBCloseGuard *)get;

+ (id<SquiDBCloseGuard_Reporter>)getReporter;

- (void)openWithNSString:(NSString *)closer;

+ (void)setEnabledWithBoolean:(jboolean)enabled;

+ (void)setReporterWithSquiDBCloseGuard_Reporter:(id<SquiDBCloseGuard_Reporter>)reporter;

- (void)warnIfOpen;

@end

J2OBJC_STATIC_INIT(SquiDBCloseGuard)

FOUNDATION_EXPORT SquiDBCloseGuard *SquiDBCloseGuard_get(void);

FOUNDATION_EXPORT void SquiDBCloseGuard_setEnabledWithBoolean_(jboolean enabled);

FOUNDATION_EXPORT void SquiDBCloseGuard_setReporterWithSquiDBCloseGuard_Reporter_(id<SquiDBCloseGuard_Reporter> reporter);

FOUNDATION_EXPORT id<SquiDBCloseGuard_Reporter> SquiDBCloseGuard_getReporter(void);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBCloseGuard)

@compatibility_alias ComYahooAndroidSqliteCloseGuard SquiDBCloseGuard;

@protocol SquiDBCloseGuard_Reporter < JavaObject >

- (void)reportWithNSString:(NSString *)message
     withJavaLangThrowable:(JavaLangThrowable *)allocationSite;

@end

J2OBJC_EMPTY_STATIC_INIT(SquiDBCloseGuard_Reporter)

J2OBJC_TYPE_LITERAL_HEADER(SquiDBCloseGuard_Reporter)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // CloseGuard_H
