//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CompileContext.java
//

#ifndef CompileContext_H
#define CompileContext_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class ComYahooSquidbUtilityVersionCode;
@protocol ComYahooSquidbSqlArgumentResolver;

@interface ComYahooSquidbSqlCompileContext : NSObject

#pragma mark Public

- (ComYahooSquidbSqlCompileContext *)clearExtraWithNSString:(NSString *)key;

+ (ComYahooSquidbSqlCompileContext *)defaultContextForVersionCodeWithComYahooSquidbUtilityVersionCode:(ComYahooSquidbUtilityVersionCode *)sqliteVersion;

- (id<ComYahooSquidbSqlArgumentResolver>)getArgumentResolver;

- (id)getExtraWithNSString:(NSString *)key;

- (ComYahooSquidbUtilityVersionCode *)getVersionCode;

- (jboolean)hasExtraWithNSString:(NSString *)key;

- (ComYahooSquidbSqlCompileContext *)setExtraWithNSString:(NSString *)key
                                                   withId:(id)value;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlCompileContext)

FOUNDATION_EXPORT ComYahooSquidbSqlCompileContext *ComYahooSquidbSqlCompileContext_defaultContextForVersionCodeWithComYahooSquidbUtilityVersionCode_(ComYahooSquidbUtilityVersionCode *sqliteVersion);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlCompileContext)

@interface ComYahooSquidbSqlCompileContext_Builder : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithComYahooSquidbUtilityVersionCode:(ComYahooSquidbUtilityVersionCode *)versionCode;

- (ComYahooSquidbSqlCompileContext *)build;

- (ComYahooSquidbSqlCompileContext_Builder *)clearExtraWithNSString:(NSString *)key;

- (ComYahooSquidbSqlCompileContext_Builder *)setArgumentResolverWithComYahooSquidbSqlArgumentResolver:(id<ComYahooSquidbSqlArgumentResolver>)argumentResolver;

- (ComYahooSquidbSqlCompileContext_Builder *)setExtraWithNSString:(NSString *)key
                                                           withId:(id)value;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlCompileContext_Builder)

FOUNDATION_EXPORT void ComYahooSquidbSqlCompileContext_Builder_initWithComYahooSquidbUtilityVersionCode_(ComYahooSquidbSqlCompileContext_Builder *self, ComYahooSquidbUtilityVersionCode *versionCode);

FOUNDATION_EXPORT ComYahooSquidbSqlCompileContext_Builder *new_ComYahooSquidbSqlCompileContext_Builder_initWithComYahooSquidbUtilityVersionCode_(ComYahooSquidbUtilityVersionCode *versionCode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlCompileContext_Builder *create_ComYahooSquidbSqlCompileContext_Builder_initWithComYahooSquidbUtilityVersionCode_(ComYahooSquidbUtilityVersionCode *versionCode);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlCompileContext_Builder)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // CompileContext_H
