//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ConjunctionCriterion.java
//

#ifndef ConjunctionCriterion_H
#define ConjunctionCriterion_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "Criterion.h"
#include "J2ObjC_header.h"

@class IOSObjectArray;
@class SquiDBOperator;
@class SquiDBSqlBuilder;
@protocol JavaUtilList;

@interface SquiDBConjunctionCriterion : SquiDBCriterion

#pragma mark Public

- (SquiDBCriterion *)and__WithSquiDBCriterion:(SquiDBCriterion *)criterion;

- (SquiDBCriterion *)or__WithSquiDBCriterion:(SquiDBCriterion *)criterion;

#pragma mark Protected

- (void)populateWithSquiDBSqlBuilder:(SquiDBSqlBuilder *)builder
                         withBoolean:(jboolean)forSqlValidation;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivateWithSquiDBOperator:(SquiDBOperator *)operator_
                                           withSquiDBCriterion:(SquiDBCriterion *)baseCriterion
                                      withSquiDBCriterionArray:(IOSObjectArray *)additionalCriterions;

- (instancetype __nonnull)initPackagePrivateWithSquiDBOperator:(SquiDBOperator *)operator_
                                              withJavaUtilList:(id<JavaUtilList>)criterions;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithSquiDBOperator:(SquiDBOperator *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SquiDBConjunctionCriterion)

FOUNDATION_EXPORT void SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withSquiDBCriterion_withSquiDBCriterionArray_(SquiDBConjunctionCriterion *self, SquiDBOperator *operator_, SquiDBCriterion *baseCriterion, IOSObjectArray *additionalCriterions);

FOUNDATION_EXPORT SquiDBConjunctionCriterion *new_SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withSquiDBCriterion_withSquiDBCriterionArray_(SquiDBOperator *operator_, SquiDBCriterion *baseCriterion, IOSObjectArray *additionalCriterions) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SquiDBConjunctionCriterion *create_SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withSquiDBCriterion_withSquiDBCriterionArray_(SquiDBOperator *operator_, SquiDBCriterion *baseCriterion, IOSObjectArray *additionalCriterions);

FOUNDATION_EXPORT void SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withJavaUtilList_(SquiDBConjunctionCriterion *self, SquiDBOperator *operator_, id<JavaUtilList> criterions);

FOUNDATION_EXPORT SquiDBConjunctionCriterion *new_SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withJavaUtilList_(SquiDBOperator *operator_, id<JavaUtilList> criterions) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SquiDBConjunctionCriterion *create_SquiDBConjunctionCriterion_initPackagePrivateWithSquiDBOperator_withJavaUtilList_(SquiDBOperator *operator_, id<JavaUtilList> criterions);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBConjunctionCriterion)

@compatibility_alias ComYahooSquidbSqlConjunctionCriterion SquiDBConjunctionCriterion;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // ConjunctionCriterion_H
