//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Criterion.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Criterion")
#ifdef RESTRICT_Criterion
#define INCLUDE_ALL_Criterion 0
#else
#define INCLUDE_ALL_Criterion 1
#endif
#undef RESTRICT_Criterion

#if !defined (ComYahooSquidbSqlCriterion_) && (INCLUDE_ALL_Criterion || defined(INCLUDE_ComYahooSquidbSqlCriterion))
#define ComYahooSquidbSqlCriterion_

#define RESTRICT_CompilableWithArguments 1
#define INCLUDE_ComYahooSquidbSqlCompilableWithArguments 1
#include "CompilableWithArguments.h"

@class ComYahooSquidbSqlOperator;
@class ComYahooSquidbSqlQuery;
@class ComYahooSquidbSqlSqlBuilder;
@class IOSObjectArray;
@protocol JavaUtilList;

@interface ComYahooSquidbSqlCriterion : ComYahooSquidbSqlCompilableWithArguments {
 @public
  ComYahooSquidbSqlOperator *operator__;
}

#pragma mark Public

- (instancetype)initWithComYahooSquidbSqlOperator:(ComYahooSquidbSqlOperator *)operator_;

- (ComYahooSquidbSqlCriterion *)and__WithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)criterion;

+ (ComYahooSquidbSqlCriterion *)and__WithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)criterion
                                withComYahooSquidbSqlCriterionArray:(IOSObjectArray *)criterions;

+ (ComYahooSquidbSqlCriterion *)and__WithJavaUtilList:(id<JavaUtilList>)criterions;

- (jboolean)isEqual:(id)o;

+ (ComYahooSquidbSqlCriterion *)existsWithComYahooSquidbSqlQuery:(ComYahooSquidbSqlQuery *)query;

+ (ComYahooSquidbSqlCriterion *)fromRawSelectionWithNSString:(NSString *)selection
                                           withNSStringArray:(IOSObjectArray *)selectionArgs;

- (NSUInteger)hash;

+ (ComYahooSquidbSqlCriterion *)literalWithId:(id)value;

- (ComYahooSquidbSqlCriterion *)negate;

+ (ComYahooSquidbSqlCriterion *)not__WithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)criterion;

- (ComYahooSquidbSqlCriterion *)or__WithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)criterion;

+ (ComYahooSquidbSqlCriterion *)or__WithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)criterion
                               withComYahooSquidbSqlCriterionArray:(IOSObjectArray *)criterions;

+ (ComYahooSquidbSqlCriterion *)or__WithJavaUtilList:(id<JavaUtilList>)criterions;

#pragma mark Protected

- (void)populateWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                    withBoolean:(jboolean)forSqlValidation;

#pragma mark Package-Private

- (void)appendToSqlBuilderWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                              withBoolean:(jboolean)forSqlValidation;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlCriterion)

J2OBJC_FIELD_SETTER(ComYahooSquidbSqlCriterion, operator__, ComYahooSquidbSqlOperator *)

FOUNDATION_EXPORT void ComYahooSquidbSqlCriterion_initWithComYahooSquidbSqlOperator_(ComYahooSquidbSqlCriterion *self, ComYahooSquidbSqlOperator *operator_);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_and__WithComYahooSquidbSqlCriterion_withComYahooSquidbSqlCriterionArray_(ComYahooSquidbSqlCriterion *criterion, IOSObjectArray *criterions);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_and__WithJavaUtilList_(id<JavaUtilList> criterions);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_or__WithComYahooSquidbSqlCriterion_withComYahooSquidbSqlCriterionArray_(ComYahooSquidbSqlCriterion *criterion, IOSObjectArray *criterions);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_or__WithJavaUtilList_(id<JavaUtilList> criterions);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_not__WithComYahooSquidbSqlCriterion_(ComYahooSquidbSqlCriterion *criterion);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_existsWithComYahooSquidbSqlQuery_(ComYahooSquidbSqlQuery *query);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_fromRawSelectionWithNSString_withNSStringArray_(NSString *selection, IOSObjectArray *selectionArgs);

FOUNDATION_EXPORT ComYahooSquidbSqlCriterion *ComYahooSquidbSqlCriterion_literalWithId_(id value);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlCriterion)

#endif

#pragma pop_macro("INCLUDE_ALL_Criterion")
