//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CursorWindow.java
//

#include "CloseGuard.h"
#include "CursorWindow.h"
#include "CursorWindowAllocationException.h"
#include "ICursor.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "SQLiteClosable.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "java/lang/annotation/Annotation.h"

#import "CursorWindowNative.h"

@interface SquiDBCursorWindow () {
 @public
  jint mStartPos_;
  NSString *mName_;
  SquiDBCloseGuard *mCloseGuard_;
}

+ (id)nativeCreateWithNSString:(NSString *)name
                       withInt:(jint)cursorWindowSize;

+ (void)nativeDisposeWithId:(id)windowPtr;

+ (void)nativeClearWithId:(id)windowPtr;

+ (jint)nativeGetNumRowsWithId:(id)windowPtr;

+ (jboolean)nativeSetNumColumnsWithId:(id)windowPtr
                              withInt:(jint)columnNum;

+ (jboolean)nativeAllocRowWithId:(id)windowPtr;

+ (void)nativeFreeLastRowWithId:(id)windowPtr;

+ (jint)nativeGetTypeWithId:(id)windowPtr
                    withInt:(jint)row
                    withInt:(jint)column;

+ (IOSByteArray *)nativeGetBlobWithId:(id)windowPtr
                              withInt:(jint)row
                              withInt:(jint)column;

+ (NSString *)nativeGetStringWithId:(id)windowPtr
                            withInt:(jint)row
                            withInt:(jint)column;

+ (jlong)nativeGetLongWithId:(id)windowPtr
                     withInt:(jint)row
                     withInt:(jint)column;

+ (jdouble)nativeGetDoubleWithId:(id)windowPtr
                         withInt:(jint)row
                         withInt:(jint)column;

+ (jboolean)nativePutBlobWithId:(id)windowPtr
                  withByteArray:(IOSByteArray *)value
                        withInt:(jint)row
                        withInt:(jint)column;

+ (jboolean)nativePutStringWithId:(id)windowPtr
                     withNSString:(NSString *)value
                          withInt:(jint)row
                          withInt:(jint)column;

+ (jboolean)nativePutLongWithId:(id)windowPtr
                       withLong:(jlong)value
                        withInt:(jint)row
                        withInt:(jint)column;

+ (jboolean)nativePutDoubleWithId:(id)windowPtr
                       withDouble:(jdouble)value
                          withInt:(jint)row
                          withInt:(jint)column;

+ (jboolean)nativePutNullWithId:(id)windowPtr
                        withInt:(jint)row
                        withInt:(jint)column;

- (void)dispose;

@end

J2OBJC_FIELD_SETTER(SquiDBCursorWindow, mName_, NSString *)
J2OBJC_FIELD_SETTER(SquiDBCursorWindow, mCloseGuard_, SquiDBCloseGuard *)

inline NSString *SquiDBCursorWindow_get_STATS_TAG(void);
static NSString *SquiDBCursorWindow_STATS_TAG = @"CursorWindowStats";
J2OBJC_STATIC_FIELD_OBJ_FINAL(SquiDBCursorWindow, STATS_TAG, NSString *)

inline jint SquiDBCursorWindow_get_sCursorWindowSize(void);
#define SquiDBCursorWindow_sCursorWindowSize 2097152
J2OBJC_STATIC_FIELD_CONSTANT(SquiDBCursorWindow, sCursorWindowSize, jint)

__attribute__((unused)) static id SquiDBCursorWindow_nativeCreateWithNSString_withInt_(NSString *name, jint cursorWindowSize);

__attribute__((unused)) static void SquiDBCursorWindow_nativeDisposeWithId_(id windowPtr);

__attribute__((unused)) static void SquiDBCursorWindow_nativeClearWithId_(id windowPtr);

__attribute__((unused)) static jint SquiDBCursorWindow_nativeGetNumRowsWithId_(id windowPtr);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativeSetNumColumnsWithId_withInt_(id windowPtr, jint columnNum);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativeAllocRowWithId_(id windowPtr);

__attribute__((unused)) static void SquiDBCursorWindow_nativeFreeLastRowWithId_(id windowPtr);

__attribute__((unused)) static jint SquiDBCursorWindow_nativeGetTypeWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static IOSByteArray *SquiDBCursorWindow_nativeGetBlobWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static NSString *SquiDBCursorWindow_nativeGetStringWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static jlong SquiDBCursorWindow_nativeGetLongWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static jdouble SquiDBCursorWindow_nativeGetDoubleWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativePutBlobWithId_withByteArray_withInt_withInt_(id windowPtr, IOSByteArray *value, jint row, jint column);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativePutStringWithId_withNSString_withInt_withInt_(id windowPtr, NSString *value, jint row, jint column);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativePutLongWithId_withLong_withInt_withInt_(id windowPtr, jlong value, jint row, jint column);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativePutDoubleWithId_withDouble_withInt_withInt_(id windowPtr, jdouble value, jint row, jint column);

__attribute__((unused)) static jboolean SquiDBCursorWindow_nativePutNullWithId_withInt_withInt_(id windowPtr, jint row, jint column);

__attribute__((unused)) static void SquiDBCursorWindow_dispose(SquiDBCursorWindow *self);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$0(void);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$1(void);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$2(void);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$3(void);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$4(void);

__attribute__((unused)) static IOSObjectArray *SquiDBCursorWindow__Annotations$5(void);

@implementation SquiDBCursorWindow

+ (id)nativeCreateWithNSString:(NSString *)name
                       withInt:(jint)cursorWindowSize {
  return SquiDBCursorWindow_nativeCreateWithNSString_withInt_(name, cursorWindowSize);
}

+ (void)nativeDisposeWithId:(id)windowPtr {
  SquiDBCursorWindow_nativeDisposeWithId_(windowPtr);
}

+ (void)nativeClearWithId:(id)windowPtr {
  SquiDBCursorWindow_nativeClearWithId_(windowPtr);
}

+ (jint)nativeGetNumRowsWithId:(id)windowPtr {
  return SquiDBCursorWindow_nativeGetNumRowsWithId_(windowPtr);
}

+ (jboolean)nativeSetNumColumnsWithId:(id)windowPtr
                              withInt:(jint)columnNum {
  return SquiDBCursorWindow_nativeSetNumColumnsWithId_withInt_(windowPtr, columnNum);
}

+ (jboolean)nativeAllocRowWithId:(id)windowPtr {
  return SquiDBCursorWindow_nativeAllocRowWithId_(windowPtr);
}

+ (void)nativeFreeLastRowWithId:(id)windowPtr {
  SquiDBCursorWindow_nativeFreeLastRowWithId_(windowPtr);
}

+ (jint)nativeGetTypeWithId:(id)windowPtr
                    withInt:(jint)row
                    withInt:(jint)column {
  return SquiDBCursorWindow_nativeGetTypeWithId_withInt_withInt_(windowPtr, row, column);
}

+ (IOSByteArray *)nativeGetBlobWithId:(id)windowPtr
                              withInt:(jint)row
                              withInt:(jint)column {
  return SquiDBCursorWindow_nativeGetBlobWithId_withInt_withInt_(windowPtr, row, column);
}

+ (NSString *)nativeGetStringWithId:(id)windowPtr
                            withInt:(jint)row
                            withInt:(jint)column {
  return SquiDBCursorWindow_nativeGetStringWithId_withInt_withInt_(windowPtr, row, column);
}

+ (jlong)nativeGetLongWithId:(id)windowPtr
                     withInt:(jint)row
                     withInt:(jint)column {
  return SquiDBCursorWindow_nativeGetLongWithId_withInt_withInt_(windowPtr, row, column);
}

+ (jdouble)nativeGetDoubleWithId:(id)windowPtr
                         withInt:(jint)row
                         withInt:(jint)column {
  return SquiDBCursorWindow_nativeGetDoubleWithId_withInt_withInt_(windowPtr, row, column);
}

+ (jboolean)nativePutBlobWithId:(id)windowPtr
                  withByteArray:(IOSByteArray *)value
                        withInt:(jint)row
                        withInt:(jint)column {
  return SquiDBCursorWindow_nativePutBlobWithId_withByteArray_withInt_withInt_(windowPtr, value, row, column);
}

+ (jboolean)nativePutStringWithId:(id)windowPtr
                     withNSString:(NSString *)value
                          withInt:(jint)row
                          withInt:(jint)column {
  return SquiDBCursorWindow_nativePutStringWithId_withNSString_withInt_withInt_(windowPtr, value, row, column);
}

+ (jboolean)nativePutLongWithId:(id)windowPtr
                       withLong:(jlong)value
                        withInt:(jint)row
                        withInt:(jint)column {
  return SquiDBCursorWindow_nativePutLongWithId_withLong_withInt_withInt_(windowPtr, value, row, column);
}

+ (jboolean)nativePutDoubleWithId:(id)windowPtr
                       withDouble:(jdouble)value
                          withInt:(jint)row
                          withInt:(jint)column {
  return SquiDBCursorWindow_nativePutDoubleWithId_withDouble_withInt_withInt_(windowPtr, value, row, column);
}

+ (jboolean)nativePutNullWithId:(id)windowPtr
                        withInt:(jint)row
                        withInt:(jint)column {
  return SquiDBCursorWindow_nativePutNullWithId_withInt_withInt_(windowPtr, row, column);
}

- (instancetype)initWithNSString:(NSString *)name {
  SquiDBCursorWindow_initWithNSString_(self, name);
  return self;
}

- (instancetype)initWithBoolean:(jboolean)localWindow {
  SquiDBCursorWindow_initWithBoolean_(self, localWindow);
  return self;
}

- (void)java_finalize {
  @try {
    if (mCloseGuard_ != nil) {
      [mCloseGuard_ warnIfOpen];
    }
    SquiDBCursorWindow_dispose(self);
  }
  @finally {
    [super java_finalize];
  }
}

- (void)dispose {
  SquiDBCursorWindow_dispose(self);
}

- (NSString *)getName {
  return mName_;
}

- (void)clear {
  [self acquireReference];
  @try {
    mStartPos_ = 0;
    SquiDBCursorWindow_nativeClearWithId_(mWindowPtr_);
  }
  @finally {
    [self releaseReference];
  }
}

- (jint)getStartPosition {
  return mStartPos_;
}

- (void)setStartPositionWithInt:(jint)pos {
  mStartPos_ = pos;
}

- (jint)getNumRows {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetNumRowsWithId_(mWindowPtr_);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)setNumColumnsWithInt:(jint)columnNum {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeSetNumColumnsWithId_withInt_(mWindowPtr_, columnNum);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)allocRow {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeAllocRowWithId_(mWindowPtr_);
  }
  @finally {
    [self releaseReference];
  }
}

- (void)freeLastRow {
  [self acquireReference];
  @try {
    SquiDBCursorWindow_nativeFreeLastRowWithId_(mWindowPtr_);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)isNullWithInt:(jint)row
                  withInt:(jint)column {
  return [self getTypeWithInt:row withInt:column] == SquiDBICursor_FIELD_TYPE_NULL;
}

- (jboolean)isBlobWithInt:(jint)row
                  withInt:(jint)column {
  jint type = [self getTypeWithInt:row withInt:column];
  return type == SquiDBICursor_FIELD_TYPE_BLOB || type == SquiDBICursor_FIELD_TYPE_NULL;
}

- (jboolean)isLongWithInt:(jint)row
                  withInt:(jint)column {
  return [self getTypeWithInt:row withInt:column] == SquiDBICursor_FIELD_TYPE_INTEGER;
}

- (jboolean)isFloatWithInt:(jint)row
                   withInt:(jint)column {
  return [self getTypeWithInt:row withInt:column] == SquiDBICursor_FIELD_TYPE_FLOAT;
}

- (jboolean)isStringWithInt:(jint)row
                    withInt:(jint)column {
  jint type = [self getTypeWithInt:row withInt:column];
  return type == SquiDBICursor_FIELD_TYPE_STRING || type == SquiDBICursor_FIELD_TYPE_NULL;
}

- (jint)getTypeWithInt:(jint)row
               withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetTypeWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (IOSByteArray *)getBlobWithInt:(jint)row
                         withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetBlobWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (NSString *)getStringWithInt:(jint)row
                       withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetStringWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jlong)getLongWithInt:(jint)row
                withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetLongWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jdouble)getDoubleWithInt:(jint)row
                    withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativeGetDoubleWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jshort)getShortWithInt:(jint)row
                  withInt:(jint)column {
  return (jshort) [self getLongWithInt:row withInt:column];
}

- (jint)getIntWithInt:(jint)row
              withInt:(jint)column {
  return (jint) [self getLongWithInt:row withInt:column];
}

- (jfloat)getFloatWithInt:(jint)row
                  withInt:(jint)column {
  return (jfloat) [self getDoubleWithInt:row withInt:column];
}

- (jboolean)putBlobWithByteArray:(IOSByteArray *)value
                         withInt:(jint)row
                         withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativePutBlobWithId_withByteArray_withInt_withInt_(mWindowPtr_, value, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)putStringWithNSString:(NSString *)value
                          withInt:(jint)row
                          withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativePutStringWithId_withNSString_withInt_withInt_(mWindowPtr_, value, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)putLongWithLong:(jlong)value
                    withInt:(jint)row
                    withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativePutLongWithId_withLong_withInt_withInt_(mWindowPtr_, value, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)putDoubleWithDouble:(jdouble)value
                        withInt:(jint)row
                        withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativePutDoubleWithId_withDouble_withInt_withInt_(mWindowPtr_, value, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (jboolean)putNullWithInt:(jint)row
                   withInt:(jint)column {
  [self acquireReference];
  @try {
    return SquiDBCursorWindow_nativePutNullWithId_withInt_withInt_(mWindowPtr_, row - mStartPos_, column);
  }
  @finally {
    [self releaseReference];
  }
}

- (void)onAllReferencesReleased {
  SquiDBCursorWindow_dispose(self);
}

- (NSString *)description {
  return JreStrcat("$$$C", [self getName], @" {", JavaLangInteger_toHexStringWithInt_(JavaLangSystem_identityHashCodeWithId_(mWindowPtr_)), '}');
}

- (void)dealloc {
  JreCheckFinalize(self, [SquiDBCursorWindow class]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x10a, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x10a, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x10a, 4, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x10a, 5, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 8, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x10a, 9, 3, -1, -1, -1, -1 },
    { NULL, "I", 0x10a, 10, 11, -1, -1, -1, -1 },
    { NULL, "[B", 0x10a, 12, 11, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x10a, 13, 11, -1, -1, -1, -1 },
    { NULL, "J", 0x10a, 14, 11, -1, -1, -1, -1 },
    { NULL, "D", 0x10a, 15, 11, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 16, 17, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 18, 19, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 20, 21, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 22, 23, -1, -1, -1, -1 },
    { NULL, "Z", 0x10a, 24, 11, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 25, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 26, -1, -1, 27, -1 },
    { NULL, "V", 0x4, 28, -1, 29, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 30, 31, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 32, 31, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 33, 34, -1, -1, 35, -1 },
    { NULL, "Z", 0x1, 36, 34, -1, -1, 37, -1 },
    { NULL, "Z", 0x1, 38, 34, -1, -1, 39, -1 },
    { NULL, "Z", 0x1, 40, 34, -1, -1, 41, -1 },
    { NULL, "Z", 0x1, 42, 34, -1, -1, 43, -1 },
    { NULL, "I", 0x1, 44, 34, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, 45, 34, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 46, 34, -1, -1, -1, -1 },
    { NULL, "J", 0x1, 47, 34, -1, -1, -1, -1 },
    { NULL, "D", 0x1, 48, 34, -1, -1, -1, -1 },
    { NULL, "S", 0x1, 49, 34, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 50, 34, -1, -1, -1, -1 },
    { NULL, "F", 0x1, 51, 34, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 52, 53, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 54, 55, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 56, 57, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 58, 59, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 60, 34, -1, -1, -1, -1 },
    { NULL, "V", 0x4, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 61, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(nativeCreateWithNSString:withInt:);
  methods[1].selector = @selector(nativeDisposeWithId:);
  methods[2].selector = @selector(nativeClearWithId:);
  methods[3].selector = @selector(nativeGetNumRowsWithId:);
  methods[4].selector = @selector(nativeSetNumColumnsWithId:withInt:);
  methods[5].selector = @selector(nativeAllocRowWithId:);
  methods[6].selector = @selector(nativeFreeLastRowWithId:);
  methods[7].selector = @selector(nativeGetTypeWithId:withInt:withInt:);
  methods[8].selector = @selector(nativeGetBlobWithId:withInt:withInt:);
  methods[9].selector = @selector(nativeGetStringWithId:withInt:withInt:);
  methods[10].selector = @selector(nativeGetLongWithId:withInt:withInt:);
  methods[11].selector = @selector(nativeGetDoubleWithId:withInt:withInt:);
  methods[12].selector = @selector(nativePutBlobWithId:withByteArray:withInt:withInt:);
  methods[13].selector = @selector(nativePutStringWithId:withNSString:withInt:withInt:);
  methods[14].selector = @selector(nativePutLongWithId:withLong:withInt:withInt:);
  methods[15].selector = @selector(nativePutDoubleWithId:withDouble:withInt:withInt:);
  methods[16].selector = @selector(nativePutNullWithId:withInt:withInt:);
  methods[17].selector = @selector(initWithNSString:);
  methods[18].selector = @selector(initWithBoolean:);
  methods[19].selector = @selector(java_finalize);
  methods[20].selector = @selector(dispose);
  methods[21].selector = @selector(getName);
  methods[22].selector = @selector(clear);
  methods[23].selector = @selector(getStartPosition);
  methods[24].selector = @selector(setStartPositionWithInt:);
  methods[25].selector = @selector(getNumRows);
  methods[26].selector = @selector(setNumColumnsWithInt:);
  methods[27].selector = @selector(allocRow);
  methods[28].selector = @selector(freeLastRow);
  methods[29].selector = @selector(isNullWithInt:withInt:);
  methods[30].selector = @selector(isBlobWithInt:withInt:);
  methods[31].selector = @selector(isLongWithInt:withInt:);
  methods[32].selector = @selector(isFloatWithInt:withInt:);
  methods[33].selector = @selector(isStringWithInt:withInt:);
  methods[34].selector = @selector(getTypeWithInt:withInt:);
  methods[35].selector = @selector(getBlobWithInt:withInt:);
  methods[36].selector = @selector(getStringWithInt:withInt:);
  methods[37].selector = @selector(getLongWithInt:withInt:);
  methods[38].selector = @selector(getDoubleWithInt:withInt:);
  methods[39].selector = @selector(getShortWithInt:withInt:);
  methods[40].selector = @selector(getIntWithInt:withInt:);
  methods[41].selector = @selector(getFloatWithInt:withInt:);
  methods[42].selector = @selector(putBlobWithByteArray:withInt:withInt:);
  methods[43].selector = @selector(putStringWithNSString:withInt:withInt:);
  methods[44].selector = @selector(putLongWithLong:withInt:withInt:);
  methods[45].selector = @selector(putDoubleWithDouble:withInt:withInt:);
  methods[46].selector = @selector(putNullWithInt:withInt:);
  methods[47].selector = @selector(onAllReferencesReleased);
  methods[48].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "STATS_TAG", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 62, -1, -1 },
    { "sCursorWindowSize", "I", .constantValue.asInt = SquiDBCursorWindow_sCursorWindowSize, 0x1a, -1, -1, -1, -1 },
    { "mWindowPtr_", "LNSObject;", .constantValue.asLong = 0, 0x1, -1, -1, -1, -1 },
    { "mStartPos_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mName_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mCloseGuard_", "LSquiDBCloseGuard;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "nativeCreate", "LNSString;I", "nativeDispose", "LNSObject;", "nativeClear", "nativeGetNumRows", "nativeSetNumColumns", "LNSObject;I", "nativeAllocRow", "nativeFreeLastRow", "nativeGetType", "LNSObject;II", "nativeGetBlob", "nativeGetString", "nativeGetLong", "nativeGetDouble", "nativePutBlob", "LNSObject;[BII", "nativePutString", "LNSObject;LNSString;II", "nativePutLong", "LNSObject;JII", "nativePutDouble", "LNSObject;DII", "nativePutNull", "LNSString;", "Z", (void *)&SquiDBCursorWindow__Annotations$0, "finalize", "LJavaLangThrowable;", "setStartPosition", "I", "setNumColumns", "isNull", "II", (void *)&SquiDBCursorWindow__Annotations$1, "isBlob", (void *)&SquiDBCursorWindow__Annotations$2, "isLong", (void *)&SquiDBCursorWindow__Annotations$3, "isFloat", (void *)&SquiDBCursorWindow__Annotations$4, "isString", (void *)&SquiDBCursorWindow__Annotations$5, "getType", "getBlob", "getString", "getLong", "getDouble", "getShort", "getInt", "getFloat", "putBlob", "[BII", "putString", "LNSString;II", "putLong", "JII", "putDouble", "DII", "putNull", "toString", &SquiDBCursorWindow_STATS_TAG };
  static const J2ObjcClassInfo _SquiDBCursorWindow = { "CursorWindow", "com.yahoo.android.sqlite", ptrTable, methods, fields, 7, 0x1, 49, 6, -1, -1, -1, -1, -1 };
  return &_SquiDBCursorWindow;
}

@end

id SquiDBCursorWindow_nativeCreateWithNSString_withInt_(NSString *name, jint cursorWindowSize) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeCreate:name cursorWindowSize:cursorWindowSize];
}

void SquiDBCursorWindow_nativeDisposeWithId_(id windowPtr) {
  SquiDBCursorWindow_initialize();
  [CursorWindowNative nativeDispose:windowPtr];
}

void SquiDBCursorWindow_nativeClearWithId_(id windowPtr) {
  SquiDBCursorWindow_initialize();
  [CursorWindowNative nativeClear:windowPtr];
}

jint SquiDBCursorWindow_nativeGetNumRowsWithId_(id windowPtr) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetNumRows:windowPtr];
}

jboolean SquiDBCursorWindow_nativeSetNumColumnsWithId_withInt_(id windowPtr, jint columnNum) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeSetNumColumns:windowPtr columnNum:columnNum];
}

jboolean SquiDBCursorWindow_nativeAllocRowWithId_(id windowPtr) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeAllocRow:windowPtr];
}

void SquiDBCursorWindow_nativeFreeLastRowWithId_(id windowPtr) {
  SquiDBCursorWindow_initialize();
  [CursorWindowNative nativeFreeLastRow:windowPtr];
}

jint SquiDBCursorWindow_nativeGetTypeWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetType:windowPtr row:row column:column];
}

IOSByteArray *SquiDBCursorWindow_nativeGetBlobWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetBlob:windowPtr row:row column:column];
}

NSString *SquiDBCursorWindow_nativeGetStringWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetString:windowPtr row:row column:column];
}

jlong SquiDBCursorWindow_nativeGetLongWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetLong:windowPtr row:row column:column];
}

jdouble SquiDBCursorWindow_nativeGetDoubleWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativeGetDouble:windowPtr row:row column:column];
}

jboolean SquiDBCursorWindow_nativePutBlobWithId_withByteArray_withInt_withInt_(id windowPtr, IOSByteArray *value, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativePutBlob:windowPtr value:value row:row column:column];
}

jboolean SquiDBCursorWindow_nativePutStringWithId_withNSString_withInt_withInt_(id windowPtr, NSString *value, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativePutString:windowPtr value:value row:row column:column];
}

jboolean SquiDBCursorWindow_nativePutLongWithId_withLong_withInt_withInt_(id windowPtr, jlong value, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativePutLong:windowPtr value:value row:row column:column];
}

jboolean SquiDBCursorWindow_nativePutDoubleWithId_withDouble_withInt_withInt_(id windowPtr, jdouble value, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativePutDouble:windowPtr value:value row:row column:column];
}

jboolean SquiDBCursorWindow_nativePutNullWithId_withInt_withInt_(id windowPtr, jint row, jint column) {
  SquiDBCursorWindow_initialize();
  return [CursorWindowNative nativePutNull:windowPtr row:row column:column];
}

void SquiDBCursorWindow_initWithNSString_(SquiDBCursorWindow *self, NSString *name) {
  SquiDBSQLiteClosable_init(self);
  self->mCloseGuard_ = SquiDBCloseGuard_get();
  self->mStartPos_ = 0;
  self->mName_ = name != nil && [name java_length] != 0 ? name : @"<unnamed>";
  self->mWindowPtr_ = SquiDBCursorWindow_nativeCreateWithNSString_withInt_(self->mName_, SquiDBCursorWindow_sCursorWindowSize);
  if (self->mWindowPtr_ == nil) {
    @throw new_SquiDBCursorWindowAllocationException_initWithNSString_(JreStrcat("$I$", @"Cursor window allocation of ", (JreIntDiv(SquiDBCursorWindow_sCursorWindowSize, 1024)), @" kb failed. "));
  }
  [((SquiDBCloseGuard *) nil_chk(self->mCloseGuard_)) openWithNSString:@"close"];
}

SquiDBCursorWindow *new_SquiDBCursorWindow_initWithNSString_(NSString *name) {
  J2OBJC_NEW_IMPL(SquiDBCursorWindow, initWithNSString_, name)
}

SquiDBCursorWindow *create_SquiDBCursorWindow_initWithNSString_(NSString *name) {
  J2OBJC_CREATE_IMPL(SquiDBCursorWindow, initWithNSString_, name)
}

void SquiDBCursorWindow_initWithBoolean_(SquiDBCursorWindow *self, jboolean localWindow) {
  SquiDBCursorWindow_initWithNSString_(self, nil);
}

SquiDBCursorWindow *new_SquiDBCursorWindow_initWithBoolean_(jboolean localWindow) {
  J2OBJC_NEW_IMPL(SquiDBCursorWindow, initWithBoolean_, localWindow)
}

SquiDBCursorWindow *create_SquiDBCursorWindow_initWithBoolean_(jboolean localWindow) {
  J2OBJC_CREATE_IMPL(SquiDBCursorWindow, initWithBoolean_, localWindow)
}

void SquiDBCursorWindow_dispose(SquiDBCursorWindow *self) {
  if (self->mCloseGuard_ != nil) {
    [self->mCloseGuard_ close];
  }
  if (self->mWindowPtr_ != nil) {
    SquiDBCursorWindow_nativeDisposeWithId_(self->mWindowPtr_);
    self->mWindowPtr_ = nil;
  }
}

IOSObjectArray *SquiDBCursorWindow__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SquiDBCursorWindow__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SquiDBCursorWindow__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SquiDBCursorWindow__Annotations$3() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SquiDBCursorWindow__Annotations$4() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SquiDBCursorWindow__Annotations$5() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBCursorWindow)

J2OBJC_NAME_MAPPING(SquiDBCursorWindow, "com.yahoo.android.sqlite", "SquiDB")
