//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Ignore.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "Ignore.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *SquiDBIgnore__Annotations$0(void);

@implementation SquiDBIgnore

- (IOSClass *)annotationType {
  return SquiDBIgnore_class_();
}

- (NSString *)description {
  return @"@com.yahoo.squidb.annotations.Ignore()";
}

- (jboolean)isEqual:(id)obj {
  return JreAnnotationEquals(self, obj);
}

- (NSUInteger)hash {
  return JreAnnotationHashCode(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { (void *)&SquiDBIgnore__Annotations$0 };
  static const J2ObjcClassInfo _SquiDBIgnore = { "Ignore", "com.yahoo.squidb.annotations", ptrTable, NULL, NULL, 7, 0x2609, 0, 0, -1, -1, -1, -1, 0 };
  return &_SquiDBIgnore;
}

@end

id<SquiDBIgnore> create_SquiDBIgnore() {
  SquiDBIgnore *self = AUTORELEASE([[SquiDBIgnore alloc] init]);
  return self;
}

IOSObjectArray *SquiDBIgnore__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray newArrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, FIELD) } count:1 type:JavaLangAnnotationElementType_class_()]) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SquiDBIgnore)

J2OBJC_NAME_MAPPING(SquiDBIgnore, "com.yahoo.squidb.annotations", "SquiDB")
