//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Join.java
//

#include "CompilableWithArguments.h"
#include "Criterion.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "Join.h"
#include "Property.h"
#include "SqlBuilder.h"
#include "SqlTable.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/StringBuilder.h"

@class SquiDBJoin_JoinType;

@interface SquiDBJoin () {
 @public
  SquiDBJoin_JoinType *joinType_;
  IOSObjectArray *criterions_;
  IOSObjectArray *usings_;
}

- (instancetype)initWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBJoin_JoinType:(SquiDBJoin_JoinType *)joinType
              withSquiDBCriterionArray:(IOSObjectArray *)criterions;

- (instancetype)initWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBJoin_JoinType:(SquiDBJoin_JoinType *)joinType
               withSquiDBPropertyArray:(IOSObjectArray *)usingColumns;

@end

J2OBJC_FIELD_SETTER(SquiDBJoin, joinType_, SquiDBJoin_JoinType *)
J2OBJC_FIELD_SETTER(SquiDBJoin, criterions_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(SquiDBJoin, usings_, IOSObjectArray *)

__attribute__((unused)) static void SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBJoin *self, SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions);

__attribute__((unused)) static SquiDBJoin *new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions) NS_RETURNS_RETAINED;

__attribute__((unused)) static SquiDBJoin *create_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions);

__attribute__((unused)) static void SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBJoin *self, SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns);

__attribute__((unused)) static SquiDBJoin *new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns) NS_RETURNS_RETAINED;

__attribute__((unused)) static SquiDBJoin *create_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns);

typedef NS_ENUM(NSUInteger, SquiDBJoin_JoinType_Enum) {
  SquiDBJoin_JoinType_Enum_INNER = 0,
  SquiDBJoin_JoinType_Enum_LEFT = 1,
  SquiDBJoin_JoinType_Enum_CROSS = 2,
};

@interface SquiDBJoin_JoinType : JavaLangEnum

@property (readonly, class, nonnull) SquiDBJoin_JoinType *INNER NS_SWIFT_NAME(INNER);
@property (readonly, class, nonnull) SquiDBJoin_JoinType *LEFT NS_SWIFT_NAME(LEFT);
@property (readonly, class, nonnull) SquiDBJoin_JoinType *CROSS NS_SWIFT_NAME(CROSS);
+ (IOSObjectArray *)values;

+ (SquiDBJoin_JoinType *)valueOfWithNSString:(NSString *)name;

- (SquiDBJoin_JoinType_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(SquiDBJoin_JoinType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT SquiDBJoin_JoinType *SquiDBJoin_JoinType_values_[];

inline SquiDBJoin_JoinType *SquiDBJoin_JoinType_get_INNER(void);
J2OBJC_ENUM_CONSTANT(SquiDBJoin_JoinType, INNER)

inline SquiDBJoin_JoinType *SquiDBJoin_JoinType_get_LEFT(void);
J2OBJC_ENUM_CONSTANT(SquiDBJoin_JoinType, LEFT)

inline SquiDBJoin_JoinType *SquiDBJoin_JoinType_get_CROSS(void);
J2OBJC_ENUM_CONSTANT(SquiDBJoin_JoinType, CROSS)

__attribute__((unused)) static void SquiDBJoin_JoinType_initWithNSString_withInt_(SquiDBJoin_JoinType *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static SquiDBJoin_JoinType *new_SquiDBJoin_JoinType_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

__attribute__((unused)) static IOSObjectArray *SquiDBJoin_JoinType_values(void);

__attribute__((unused)) static SquiDBJoin_JoinType *SquiDBJoin_JoinType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT SquiDBJoin_JoinType *SquiDBJoin_JoinType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBJoin_JoinType)

@implementation SquiDBJoin

- (instancetype)initWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBJoin_JoinType:(SquiDBJoin_JoinType *)joinType
              withSquiDBCriterionArray:(IOSObjectArray *)criterions {
  SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(self, table, joinType, criterions);
  return self;
}

- (instancetype)initWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBJoin_JoinType:(SquiDBJoin_JoinType *)joinType
               withSquiDBPropertyArray:(IOSObjectArray *)usingColumns {
  SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(self, table, joinType, usingColumns);
  return self;
}

+ (SquiDBJoin *)innerWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBCriterionArray:(IOSObjectArray *)criterions {
  return SquiDBJoin_innerWithSquiDBSqlTable_withSquiDBCriterionArray_(table, criterions);
}

+ (SquiDBJoin *)innerWithSquiDBSqlTable:(SquiDBSqlTable *)table
                withSquiDBPropertyArray:(IOSObjectArray *)usingColumns {
  return SquiDBJoin_innerWithSquiDBSqlTable_withSquiDBPropertyArray_(table, usingColumns);
}

+ (SquiDBJoin *)leftWithSquiDBSqlTable:(SquiDBSqlTable *)table
              withSquiDBCriterionArray:(IOSObjectArray *)criterions {
  return SquiDBJoin_leftWithSquiDBSqlTable_withSquiDBCriterionArray_(table, criterions);
}

+ (SquiDBJoin *)leftWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBPropertyArray:(IOSObjectArray *)usingColumns {
  return SquiDBJoin_leftWithSquiDBSqlTable_withSquiDBPropertyArray_(table, usingColumns);
}

+ (SquiDBJoin *)crossWithSquiDBSqlTable:(SquiDBSqlTable *)table
               withSquiDBCriterionArray:(IOSObjectArray *)criterions {
  return SquiDBJoin_crossWithSquiDBSqlTable_withSquiDBCriterionArray_(table, criterions);
}

+ (SquiDBJoin *)crossWithSquiDBSqlTable:(SquiDBSqlTable *)table
                withSquiDBPropertyArray:(IOSObjectArray *)usingColumns {
  return SquiDBJoin_crossWithSquiDBSqlTable_withSquiDBPropertyArray_(table, usingColumns);
}

- (void)appendToSqlBuilderWithSquiDBSqlBuilder:(SquiDBSqlBuilder *)builder
                                   withBoolean:(jboolean)forSqlValidation {
  (void) [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk(((SquiDBSqlBuilder *) nil_chk(builder))->sql_)) appendWithId:joinType_])) appendWithNSString:@" JOIN "];
  [((SquiDBSqlTable *) nil_chk(joinTable_)) appendToSqlBuilderWithSquiDBSqlBuilder:builder withBoolean:forSqlValidation];
  (void) [builder->sql_ appendWithNSString:@" "];
  if (criterions_ != nil && criterions_->size_ > 0) {
    (void) [builder->sql_ appendWithNSString:@"ON "];
    for (jint i = 0; i < criterions_->size_; i++) {
      if (i > 0) {
        (void) [builder->sql_ appendWithNSString:@" AND "];
      }
      [((SquiDBCriterion *) nil_chk(IOSObjectArray_Get(criterions_, i))) appendToSqlBuilderWithSquiDBSqlBuilder:builder withBoolean:forSqlValidation];
    }
  }
  else if (usings_ != nil && usings_->size_ > 0) {
    (void) [builder->sql_ appendWithNSString:@"USING ("];
    for (jint i = 0; i < usings_->size_; i++) {
      if (i > 0) {
        (void) [builder->sql_ appendWithNSString:@", "];
      }
      (void) [builder->sql_ appendWithNSString:[((SquiDBProperty *) nil_chk(IOSObjectArray_Get(usings_, i))) getExpression]];
    }
    (void) [builder->sql_ appendWithNSString:@")"];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x82, -1, 0, -1, 1, -1, -1 },
    { NULL, NULL, 0x82, -1, 2, -1, 3, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 4, 5, -1, 6, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 4, 7, -1, 8, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 9, 5, -1, 6, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 9, 7, -1, 8, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 10, 5, -1, 6, -1, -1 },
    { NULL, "LSquiDBJoin;", 0x89, 10, 7, -1, 8, -1, -1 },
    { NULL, "V", 0x0, 11, 12, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithSquiDBSqlTable:withSquiDBJoin_JoinType:withSquiDBCriterionArray:);
  methods[1].selector = @selector(initWithSquiDBSqlTable:withSquiDBJoin_JoinType:withSquiDBPropertyArray:);
  methods[2].selector = @selector(innerWithSquiDBSqlTable:withSquiDBCriterionArray:);
  methods[3].selector = @selector(innerWithSquiDBSqlTable:withSquiDBPropertyArray:);
  methods[4].selector = @selector(leftWithSquiDBSqlTable:withSquiDBCriterionArray:);
  methods[5].selector = @selector(leftWithSquiDBSqlTable:withSquiDBPropertyArray:);
  methods[6].selector = @selector(crossWithSquiDBSqlTable:withSquiDBCriterionArray:);
  methods[7].selector = @selector(crossWithSquiDBSqlTable:withSquiDBPropertyArray:);
  methods[8].selector = @selector(appendToSqlBuilderWithSquiDBSqlBuilder:withBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "joinTable_", "LSquiDBSqlTable;", .constantValue.asLong = 0, 0x10, -1, -1, 13, -1 },
    { "joinType_", "LSquiDBJoin_JoinType;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "criterions_", "[LSquiDBCriterion;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "usings_", "[LSquiDBProperty;", .constantValue.asLong = 0, 0x12, -1, -1, 14, -1 },
  };
  static const void *ptrTable[] = { "LSquiDBSqlTable;LSquiDBJoin_JoinType;[LSquiDBCriterion;", "(Lcom/yahoo/squidb/sql/SqlTable<*>;Lcom/yahoo/squidb/sql/Join$JoinType;[Lcom/yahoo/squidb/sql/Criterion;)V", "LSquiDBSqlTable;LSquiDBJoin_JoinType;[LSquiDBProperty;", "(Lcom/yahoo/squidb/sql/SqlTable<*>;Lcom/yahoo/squidb/sql/Join$JoinType;[Lcom/yahoo/squidb/sql/Property<*>;)V", "inner", "LSquiDBSqlTable;[LSquiDBCriterion;", "(Lcom/yahoo/squidb/sql/SqlTable<*>;[Lcom/yahoo/squidb/sql/Criterion;)Lcom/yahoo/squidb/sql/Join;", "LSquiDBSqlTable;[LSquiDBProperty;", "(Lcom/yahoo/squidb/sql/SqlTable<*>;[Lcom/yahoo/squidb/sql/Property<*>;)Lcom/yahoo/squidb/sql/Join;", "left", "cross", "appendToSqlBuilder", "LSquiDBSqlBuilder;Z", "Lcom/yahoo/squidb/sql/SqlTable<*>;", "[Lcom/yahoo/squidb/sql/Property<*>;", "LSquiDBJoin_JoinType;" };
  static const J2ObjcClassInfo _SquiDBJoin = { "Join", "com.yahoo.squidb.sql", ptrTable, methods, fields, 7, 0x1, 9, 4, -1, 15, -1, -1, -1 };
  return &_SquiDBJoin;
}

@end

void SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBJoin *self, SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions) {
  SquiDBCompilableWithArguments_initPackagePrivate(self);
  self->joinTable_ = table;
  self->joinType_ = joinType;
  self->criterions_ = criterions;
  self->usings_ = nil;
}

SquiDBJoin *new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions) {
  J2OBJC_NEW_IMPL(SquiDBJoin, initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_, table, joinType, criterions)
}

SquiDBJoin *create_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *criterions) {
  J2OBJC_CREATE_IMPL(SquiDBJoin, initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_, table, joinType, criterions)
}

void SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBJoin *self, SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns) {
  SquiDBCompilableWithArguments_initPackagePrivate(self);
  self->joinTable_ = table;
  self->joinType_ = joinType;
  self->usings_ = usingColumns;
  self->criterions_ = nil;
}

SquiDBJoin *new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns) {
  J2OBJC_NEW_IMPL(SquiDBJoin, initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_, table, joinType, usingColumns)
}

SquiDBJoin *create_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(SquiDBSqlTable *table, SquiDBJoin_JoinType *joinType, IOSObjectArray *usingColumns) {
  J2OBJC_CREATE_IMPL(SquiDBJoin, initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_, table, joinType, usingColumns)
}

SquiDBJoin *SquiDBJoin_innerWithSquiDBSqlTable_withSquiDBCriterionArray_(SquiDBSqlTable *table, IOSObjectArray *criterions) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(table, JreLoadEnum(SquiDBJoin_JoinType, INNER), criterions);
}

SquiDBJoin *SquiDBJoin_innerWithSquiDBSqlTable_withSquiDBPropertyArray_(SquiDBSqlTable *table, IOSObjectArray *usingColumns) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(table, JreLoadEnum(SquiDBJoin_JoinType, INNER), usingColumns);
}

SquiDBJoin *SquiDBJoin_leftWithSquiDBSqlTable_withSquiDBCriterionArray_(SquiDBSqlTable *table, IOSObjectArray *criterions) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(table, JreLoadEnum(SquiDBJoin_JoinType, LEFT), criterions);
}

SquiDBJoin *SquiDBJoin_leftWithSquiDBSqlTable_withSquiDBPropertyArray_(SquiDBSqlTable *table, IOSObjectArray *usingColumns) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(table, JreLoadEnum(SquiDBJoin_JoinType, LEFT), usingColumns);
}

SquiDBJoin *SquiDBJoin_crossWithSquiDBSqlTable_withSquiDBCriterionArray_(SquiDBSqlTable *table, IOSObjectArray *criterions) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBCriterionArray_(table, JreLoadEnum(SquiDBJoin_JoinType, CROSS), criterions);
}

SquiDBJoin *SquiDBJoin_crossWithSquiDBSqlTable_withSquiDBPropertyArray_(SquiDBSqlTable *table, IOSObjectArray *usingColumns) {
  SquiDBJoin_initialize();
  return new_SquiDBJoin_initWithSquiDBSqlTable_withSquiDBJoin_JoinType_withSquiDBPropertyArray_(table, JreLoadEnum(SquiDBJoin_JoinType, CROSS), usingColumns);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBJoin)

J2OBJC_NAME_MAPPING(SquiDBJoin, "com.yahoo.squidb.sql", "SquiDB")

J2OBJC_INITIALIZED_DEFN(SquiDBJoin_JoinType)

SquiDBJoin_JoinType *SquiDBJoin_JoinType_values_[3];

@implementation SquiDBJoin_JoinType

+ (SquiDBJoin_JoinType *)INNER {
  return JreEnum(SquiDBJoin_JoinType, INNER);
}

+ (SquiDBJoin_JoinType *)LEFT {
  return JreEnum(SquiDBJoin_JoinType, LEFT);
}

+ (SquiDBJoin_JoinType *)CROSS {
  return JreEnum(SquiDBJoin_JoinType, CROSS);
}

+ (IOSObjectArray *)values {
  return SquiDBJoin_JoinType_values();
}

+ (SquiDBJoin_JoinType *)valueOfWithNSString:(NSString *)name {
  return SquiDBJoin_JoinType_valueOfWithNSString_(name);
}

- (SquiDBJoin_JoinType_Enum)toNSEnum {
  return (SquiDBJoin_JoinType_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LSquiDBJoin_JoinType;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LSquiDBJoin_JoinType;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "INNER", "LSquiDBJoin_JoinType;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "LEFT", "LSquiDBJoin_JoinType;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "CROSS", "LSquiDBJoin_JoinType;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(SquiDBJoin_JoinType, INNER), &JreEnum(SquiDBJoin_JoinType, LEFT), &JreEnum(SquiDBJoin_JoinType, CROSS), "LSquiDBJoin;", "Ljava/lang/Enum<Lcom/yahoo/squidb/sql/Join$JoinType;>;" };
  static const J2ObjcClassInfo _SquiDBJoin_JoinType = { "JoinType", "com.yahoo.squidb.sql", ptrTable, methods, fields, 7, 0x401a, 2, 3, 5, -1, -1, 6, -1 };
  return &_SquiDBJoin_JoinType;
}

+ (void)initialize {
  if (self == [SquiDBJoin_JoinType class]) {
    JreEnum(SquiDBJoin_JoinType, INNER) = new_SquiDBJoin_JoinType_initWithNSString_withInt_(JreEnumConstantName(SquiDBJoin_JoinType_class_(), 0), 0);
    JreEnum(SquiDBJoin_JoinType, LEFT) = new_SquiDBJoin_JoinType_initWithNSString_withInt_(JreEnumConstantName(SquiDBJoin_JoinType_class_(), 1), 1);
    JreEnum(SquiDBJoin_JoinType, CROSS) = new_SquiDBJoin_JoinType_initWithNSString_withInt_(JreEnumConstantName(SquiDBJoin_JoinType_class_(), 2), 2);
    J2OBJC_SET_INITIALIZED(SquiDBJoin_JoinType)
  }
}

@end

void SquiDBJoin_JoinType_initWithNSString_withInt_(SquiDBJoin_JoinType *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

SquiDBJoin_JoinType *new_SquiDBJoin_JoinType_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  J2OBJC_NEW_IMPL(SquiDBJoin_JoinType, initWithNSString_withInt_, __name, __ordinal)
}

IOSObjectArray *SquiDBJoin_JoinType_values() {
  SquiDBJoin_JoinType_initialize();
  return [IOSObjectArray arrayWithObjects:SquiDBJoin_JoinType_values_ count:3 type:SquiDBJoin_JoinType_class_()];
}

SquiDBJoin_JoinType *SquiDBJoin_JoinType_valueOfWithNSString_(NSString *name) {
  SquiDBJoin_JoinType_initialize();
  for (int i = 0; i < 3; i++) {
    SquiDBJoin_JoinType *e = SquiDBJoin_JoinType_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

SquiDBJoin_JoinType *SquiDBJoin_JoinType_fromOrdinal(NSUInteger ordinal) {
  SquiDBJoin_JoinType_initialize();
  if (ordinal >= 3) {
    return nil;
  }
  return SquiDBJoin_JoinType_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBJoin_JoinType)
