//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/NegationCriterion.java
//

#ifndef NegationCriterion_H
#define NegationCriterion_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "Criterion.h"
#include "J2ObjC_header.h"

@class ComYahooSquidbSqlOperator;
@class ComYahooSquidbSqlSqlBuilder;

@interface ComYahooSquidbSqlNegationCriterion : ComYahooSquidbSqlCriterion

#pragma mark Public

- (ComYahooSquidbSqlCriterion *)negate;

#pragma mark Protected

- (void)populateWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                    withBoolean:(jboolean)forSqlValidation;

#pragma mark Package-Private

- (instancetype __nonnull)initWithComYahooSquidbSqlCriterion:(ComYahooSquidbSqlCriterion *)toNegate;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithComYahooSquidbSqlOperator:(ComYahooSquidbSqlOperator *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlNegationCriterion)

FOUNDATION_EXPORT void ComYahooSquidbSqlNegationCriterion_initWithComYahooSquidbSqlCriterion_(ComYahooSquidbSqlNegationCriterion *self, ComYahooSquidbSqlCriterion *toNegate);

FOUNDATION_EXPORT ComYahooSquidbSqlNegationCriterion *new_ComYahooSquidbSqlNegationCriterion_initWithComYahooSquidbSqlCriterion_(ComYahooSquidbSqlCriterion *toNegate) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlNegationCriterion *create_ComYahooSquidbSqlNegationCriterion_initWithComYahooSquidbSqlCriterion_(ComYahooSquidbSqlCriterion *toNegate);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlNegationCriterion)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // NegationCriterion_H
