//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/OperationCanceledException.java
//

#include "J2ObjC_source.h"
#include "OperationCanceledException.h"
#include "java/lang/RuntimeException.h"

@implementation SquiDBOperationCanceledException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  SquiDBOperationCanceledException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)message {
  SquiDBOperationCanceledException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _SquiDBOperationCanceledException = { "OperationCanceledException", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_SquiDBOperationCanceledException;
}

@end

void SquiDBOperationCanceledException_init(SquiDBOperationCanceledException *self) {
  SquiDBOperationCanceledException_initWithNSString_(self, nil);
}

SquiDBOperationCanceledException *new_SquiDBOperationCanceledException_init() {
  J2OBJC_NEW_IMPL(SquiDBOperationCanceledException, init)
}

SquiDBOperationCanceledException *create_SquiDBOperationCanceledException_init() {
  J2OBJC_CREATE_IMPL(SquiDBOperationCanceledException, init)
}

void SquiDBOperationCanceledException_initWithNSString_(SquiDBOperationCanceledException *self, NSString *message) {
  JavaLangRuntimeException_initWithNSString_(self, message != nil ? message : @"The operation has been canceled.");
}

SquiDBOperationCanceledException *new_SquiDBOperationCanceledException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(SquiDBOperationCanceledException, initWithNSString_, message)
}

SquiDBOperationCanceledException *create_SquiDBOperationCanceledException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(SquiDBOperationCanceledException, initWithNSString_, message)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBOperationCanceledException)

J2OBJC_NAME_MAPPING(SquiDBOperationCanceledException, "com.yahoo.android.sqlite", "SquiDB")
