//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Printer.java
//

#include "J2ObjC_source.h"
#include "Printer.h"

@interface ComYahooAndroidSqlitePrinter : NSObject

@end

@implementation ComYahooAndroidSqlitePrinter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(printlnWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "println", "LNSString;" };
  static const J2ObjcClassInfo _ComYahooAndroidSqlitePrinter = { "Printer", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_ComYahooAndroidSqlitePrinter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComYahooAndroidSqlitePrinter)
