//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/RawFunction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RawFunction")
#ifdef RESTRICT_RawFunction
#define INCLUDE_ALL_RawFunction 0
#else
#define INCLUDE_ALL_RawFunction 1
#endif
#undef RESTRICT_RawFunction

#if !defined (ComYahooSquidbSqlRawFunction_) && (INCLUDE_ALL_RawFunction || defined(INCLUDE_ComYahooSquidbSqlRawFunction))
#define ComYahooSquidbSqlRawFunction_

#define RESTRICT_Function 1
#define INCLUDE_ComYahooSquidbSqlFunction 1
#include "Function.h"

@class ComYahooSquidbSqlField;
@class ComYahooSquidbSqlSqlBuilder;

@interface ComYahooSquidbSqlRawFunction : ComYahooSquidbSqlFunction

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)expression;

- (ComYahooSquidbSqlField *)asWithNSString:(NSString *)arg0;

- (NSString *)getExpression;

#pragma mark Protected

- (void)appendFunctionExpressionWithComYahooSquidbSqlSqlBuilder:(ComYahooSquidbSqlSqlBuilder *)builder
                                                    withBoolean:(jboolean)forSqlValidation;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlRawFunction)

FOUNDATION_EXPORT void ComYahooSquidbSqlRawFunction_initWithNSString_(ComYahooSquidbSqlRawFunction *self, NSString *expression);

FOUNDATION_EXPORT ComYahooSquidbSqlRawFunction *new_ComYahooSquidbSqlRawFunction_initWithNSString_(NSString *expression) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlRawFunction *create_ComYahooSquidbSqlRawFunction_initWithNSString_(NSString *expression);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlRawFunction)

#endif

#pragma pop_macro("INCLUDE_ALL_RawFunction")
