//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteAbortException.java
//

#include "J2ObjC_source.h"
#include "SQLiteAbortException.h"
#include "SQLiteException.h"

@implementation ComYahooAndroidSqliteSQLiteAbortException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComYahooAndroidSqliteSQLiteAbortException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteAbortException = { "SQLiteAbortException", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComYahooAndroidSqliteSQLiteAbortException;
}

@end

void ComYahooAndroidSqliteSQLiteAbortException_init(ComYahooAndroidSqliteSQLiteAbortException *self) {
  ComYahooAndroidSqliteSQLiteException_init(self);
}

ComYahooAndroidSqliteSQLiteAbortException *new_ComYahooAndroidSqliteSQLiteAbortException_init() {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteAbortException, init)
}

ComYahooAndroidSqliteSQLiteAbortException *create_ComYahooAndroidSqliteSQLiteAbortException_init() {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteAbortException, init)
}

void ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(ComYahooAndroidSqliteSQLiteAbortException *self, NSString *error) {
  ComYahooAndroidSqliteSQLiteException_initWithNSString_(self, error);
}

ComYahooAndroidSqliteSQLiteAbortException *new_ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteAbortException, initWithNSString_, error)
}

ComYahooAndroidSqliteSQLiteAbortException *create_ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteAbortException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteAbortException)
