//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteConnection.java
//

#ifndef SQLiteConnection_H
#define SQLiteConnection_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class IOSObjectArray;
@class JavaUtilArrayList;
@class SquiDBCursorWindow;
@class SquiDBSQLiteConnectionPool;
@class SquiDBSQLiteDatabaseConfiguration;
@class SquiDBSQLiteStatementInfo;
@protocol SquiDBPrinter;

@interface SquiDBSQLiteConnection : NSObject

#pragma mark Public

- (void)dumpWithSquiDBPrinter:(id<SquiDBPrinter>)printer
                  withBoolean:(jboolean)verbose;

- (void)executeWithNSString:(NSString *)sql
          withNSObjectArray:(IOSObjectArray *)bindArgs;

- (jint)executeForChangedRowCountWithNSString:(NSString *)sql
                            withNSObjectArray:(IOSObjectArray *)bindArgs;

- (jint)executeForCursorWindowWithNSString:(NSString *)sql
                         withNSObjectArray:(IOSObjectArray *)bindArgs
                    withSquiDBCursorWindow:(SquiDBCursorWindow *)window
                                   withInt:(jint)startPos
                                   withInt:(jint)requiredPos
                               withBoolean:(jboolean)countAllRows;

- (jlong)executeForLastInsertedRowIdWithNSString:(NSString *)sql
                               withNSObjectArray:(IOSObjectArray *)bindArgs;

- (jlong)executeForLongWithNSString:(NSString *)sql
                  withNSObjectArray:(IOSObjectArray *)bindArgs;

- (NSString *)executeForStringWithNSString:(NSString *)sql
                         withNSObjectArray:(IOSObjectArray *)bindArgs;

- (jint)getConnectionId;

- (jboolean)isPrimaryConnection;

- (void)prepareWithNSString:(NSString *)sql
withSquiDBSQLiteStatementInfo:(SquiDBSQLiteStatementInfo *)outStatementInfo;

- (NSString *)description;

#pragma mark Protected

- (void)java_finalize;

#pragma mark Package-Private

- (void)close;

- (void)collectDbStatsWithJavaUtilArrayList:(JavaUtilArrayList *)dbStatsList;

- (void)collectDbStatsUnsafeWithJavaUtilArrayList:(JavaUtilArrayList *)dbStatsList;

- (NSString *)describeCurrentOperationUnsafe;

- (void)dumpUnsafeWithSquiDBPrinter:(id<SquiDBPrinter>)printer
                        withBoolean:(jboolean)verbose;

- (jboolean)isPreparedStatementInCacheWithNSString:(NSString *)sql;

+ (SquiDBSQLiteConnection *)openWithSquiDBSQLiteConnectionPool:(SquiDBSQLiteConnectionPool *)pool
                         withSquiDBSQLiteDatabaseConfiguration:(SquiDBSQLiteDatabaseConfiguration *)configuration
                                                       withInt:(jint)connectionId
                                                   withBoolean:(jboolean)primaryConnection;

- (void)reconfigureWithSquiDBSQLiteDatabaseConfiguration:(SquiDBSQLiteDatabaseConfiguration *)configuration;

- (void)setOnlyAllowReadOnlyOperationsWithBoolean:(jboolean)readOnly;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(SquiDBSQLiteConnection)

FOUNDATION_EXPORT SquiDBSQLiteConnection *SquiDBSQLiteConnection_openWithSquiDBSQLiteConnectionPool_withSquiDBSQLiteDatabaseConfiguration_withInt_withBoolean_(SquiDBSQLiteConnectionPool *pool, SquiDBSQLiteDatabaseConfiguration *configuration, jint connectionId, jboolean primaryConnection);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBSQLiteConnection)

@compatibility_alias ComYahooAndroidSqliteSQLiteConnection SquiDBSQLiteConnection;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // SQLiteConnection_H
