//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteDatabaseCorruptException.java
//

#include "J2ObjC_source.h"
#include "SQLiteDatabaseCorruptException.h"
#include "SQLiteException.h"

@implementation ComYahooAndroidSqliteSQLiteDatabaseCorruptException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComYahooAndroidSqliteSQLiteDatabaseCorruptException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  ComYahooAndroidSqliteSQLiteDatabaseCorruptException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteDatabaseCorruptException = { "SQLiteDatabaseCorruptException", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComYahooAndroidSqliteSQLiteDatabaseCorruptException;
}

@end

void ComYahooAndroidSqliteSQLiteDatabaseCorruptException_init(ComYahooAndroidSqliteSQLiteDatabaseCorruptException *self) {
  ComYahooAndroidSqliteSQLiteException_init(self);
}

ComYahooAndroidSqliteSQLiteDatabaseCorruptException *new_ComYahooAndroidSqliteSQLiteDatabaseCorruptException_init() {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteDatabaseCorruptException, init)
}

ComYahooAndroidSqliteSQLiteDatabaseCorruptException *create_ComYahooAndroidSqliteSQLiteDatabaseCorruptException_init() {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteDatabaseCorruptException, init)
}

void ComYahooAndroidSqliteSQLiteDatabaseCorruptException_initWithNSString_(ComYahooAndroidSqliteSQLiteDatabaseCorruptException *self, NSString *error) {
  ComYahooAndroidSqliteSQLiteException_initWithNSString_(self, error);
}

ComYahooAndroidSqliteSQLiteDatabaseCorruptException *new_ComYahooAndroidSqliteSQLiteDatabaseCorruptException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteDatabaseCorruptException, initWithNSString_, error)
}

ComYahooAndroidSqliteSQLiteDatabaseCorruptException *create_ComYahooAndroidSqliteSQLiteDatabaseCorruptException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteDatabaseCorruptException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteDatabaseCorruptException)
