//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteCursorDriver.java
//

#include "J2ObjC_source.h"
#include "SQLiteCursorDriver.h"

@interface SquiDBSQLiteCursorDriver : NSObject

@end

@implementation SquiDBSQLiteCursorDriver

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LSquiDBICursor;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(queryWithSquiDBSQLiteDatabase_CursorFactory:withNSStringArray:);
  methods[1].selector = @selector(cursorDeactivated);
  methods[2].selector = @selector(cursorRequeriedWithSquiDBICursor:);
  methods[3].selector = @selector(cursorClosed);
  methods[4].selector = @selector(setBindArgumentsWithNSStringArray:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "query", "LSquiDBSQLiteDatabase_CursorFactory;[LNSString;", "cursorRequeried", "LSquiDBICursor;", "setBindArguments", "[LNSString;" };
  static const J2ObjcClassInfo _SquiDBSQLiteCursorDriver = { "SQLiteCursorDriver", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x609, 5, 0, -1, -1, -1, -1, -1 };
  return &_SquiDBSQLiteCursorDriver;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SquiDBSQLiteCursorDriver)

J2OBJC_NAME_MAPPING(SquiDBSQLiteCursorDriver, "com.yahoo.android.sqlite", "SquiDB")
