//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteDirectCursorDriver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SQLiteDirectCursorDriver")
#ifdef RESTRICT_SQLiteDirectCursorDriver
#define INCLUDE_ALL_SQLiteDirectCursorDriver 0
#else
#define INCLUDE_ALL_SQLiteDirectCursorDriver 1
#endif
#undef RESTRICT_SQLiteDirectCursorDriver

#if !defined (ComYahooAndroidSqliteSQLiteDirectCursorDriver_) && (INCLUDE_ALL_SQLiteDirectCursorDriver || defined(INCLUDE_ComYahooAndroidSqliteSQLiteDirectCursorDriver))
#define ComYahooAndroidSqliteSQLiteDirectCursorDriver_

#define RESTRICT_SQLiteCursorDriver 1
#define INCLUDE_ComYahooAndroidSqliteSQLiteCursorDriver 1
#include "SQLiteCursorDriver.h"

@class ComYahooAndroidSqliteSQLiteDatabase;
@class IOSObjectArray;
@protocol ComYahooAndroidSqliteSQLiteDatabase_CursorFactory;
@protocol ComYahooSquidbDataICursor;

@interface ComYahooAndroidSqliteSQLiteDirectCursorDriver : NSObject < ComYahooAndroidSqliteSQLiteCursorDriver >

#pragma mark Public

- (instancetype)initWithComYahooAndroidSqliteSQLiteDatabase:(ComYahooAndroidSqliteSQLiteDatabase *)db
                                               withNSString:(NSString *)sql
                                               withNSString:(NSString *)editTable;

- (void)cursorClosed;

- (void)cursorDeactivated;

- (void)cursorRequeriedWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor;

- (id<ComYahooSquidbDataICursor>)queryWithComYahooAndroidSqliteSQLiteDatabase_CursorFactory:(id<ComYahooAndroidSqliteSQLiteDatabase_CursorFactory>)factory
                                                                          withNSStringArray:(IOSObjectArray *)selectionArgs;

- (void)setBindArgumentsWithNSStringArray:(IOSObjectArray *)bindArgs;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteSQLiteDirectCursorDriver)

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteDirectCursorDriver_initWithComYahooAndroidSqliteSQLiteDatabase_withNSString_withNSString_(ComYahooAndroidSqliteSQLiteDirectCursorDriver *self, ComYahooAndroidSqliteSQLiteDatabase *db, NSString *sql, NSString *editTable);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteDirectCursorDriver *new_ComYahooAndroidSqliteSQLiteDirectCursorDriver_initWithComYahooAndroidSqliteSQLiteDatabase_withNSString_withNSString_(ComYahooAndroidSqliteSQLiteDatabase *db, NSString *sql, NSString *editTable) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteDirectCursorDriver *create_ComYahooAndroidSqliteSQLiteDirectCursorDriver_initWithComYahooAndroidSqliteSQLiteDatabase_withNSString_withNSString_(ComYahooAndroidSqliteSQLiteDatabase *db, NSString *sql, NSString *editTable);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteSQLiteDirectCursorDriver)

#endif

#pragma pop_macro("INCLUDE_ALL_SQLiteDirectCursorDriver")
