//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteDoneException.java
//

#include "J2ObjC_source.h"
#include "SQLiteDoneException.h"
#include "SQLiteException.h"

@implementation SquiDBSQLiteDoneException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  SquiDBSQLiteDoneException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  SquiDBSQLiteDoneException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _SquiDBSQLiteDoneException = { "SQLiteDoneException", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_SquiDBSQLiteDoneException;
}

@end

void SquiDBSQLiteDoneException_init(SquiDBSQLiteDoneException *self) {
  SquiDBSQLiteException_init(self);
}

SquiDBSQLiteDoneException *new_SquiDBSQLiteDoneException_init() {
  J2OBJC_NEW_IMPL(SquiDBSQLiteDoneException, init)
}

SquiDBSQLiteDoneException *create_SquiDBSQLiteDoneException_init() {
  J2OBJC_CREATE_IMPL(SquiDBSQLiteDoneException, init)
}

void SquiDBSQLiteDoneException_initWithNSString_(SquiDBSQLiteDoneException *self, NSString *error) {
  SquiDBSQLiteException_initWithNSString_(self, error);
}

SquiDBSQLiteDoneException *new_SquiDBSQLiteDoneException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(SquiDBSQLiteDoneException, initWithNSString_, error)
}

SquiDBSQLiteDoneException *create_SquiDBSQLiteDoneException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(SquiDBSQLiteDoneException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBSQLiteDoneException)

J2OBJC_NAME_MAPPING(SquiDBSQLiteDoneException, "com.yahoo.android.sqlite", "SquiDB")
