//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteOpenHelper.java
//

#include "DatabaseErrorHandler.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Logger.h"
#include "SQLiteCantOpenDatabaseException.h"
#include "SQLiteDatabase.h"
#include "SQLiteException.h"
#include "SQLiteOpenHelper.h"
#include "java/io/File.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"

@interface SquiDBSQLiteOpenHelper () {
 @public
  NSString *mPath_;
  NSString *mName_;
  JavaIoFile *mDatabasePath_;
  id<SquiDBSQLiteDatabase_CursorFactory> mFactory_;
  jint mNewVersion_;
  SquiDBSQLiteDatabase *mDatabase_;
  jboolean mIsInitializing_;
  jboolean mEnableWriteAheadLogging_;
  id<SquiDBDatabaseErrorHandler> mErrorHandler_;
}

- (SquiDBSQLiteDatabase *)getDatabaseLockedWithBoolean:(jboolean)writable;

@end

J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mPath_, NSString *)
J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mName_, NSString *)
J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mDatabasePath_, JavaIoFile *)
J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mFactory_, id<SquiDBSQLiteDatabase_CursorFactory>)
J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mDatabase_, SquiDBSQLiteDatabase *)
J2OBJC_FIELD_SETTER(SquiDBSQLiteOpenHelper, mErrorHandler_, id<SquiDBDatabaseErrorHandler>)

inline NSString *SquiDBSQLiteOpenHelper_get_TAG(void);
static NSString *SquiDBSQLiteOpenHelper_TAG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(SquiDBSQLiteOpenHelper, TAG, NSString *)

inline jboolean SquiDBSQLiteOpenHelper_get_DEBUG_STRICT_READONLY(void);
#define SquiDBSQLiteOpenHelper_DEBUG_STRICT_READONLY false
J2OBJC_STATIC_FIELD_CONSTANT(SquiDBSQLiteOpenHelper, DEBUG_STRICT_READONLY, jboolean)

__attribute__((unused)) static SquiDBSQLiteDatabase *SquiDBSQLiteOpenHelper_getDatabaseLockedWithBoolean_(SquiDBSQLiteOpenHelper *self, jboolean writable);

J2OBJC_INITIALIZED_DEFN(SquiDBSQLiteOpenHelper)

@implementation SquiDBSQLiteOpenHelper

- (instancetype)initWithNSString:(NSString *)path
                    withNSString:(NSString *)name
withSquiDBSQLiteDatabase_CursorFactory:(id<SquiDBSQLiteDatabase_CursorFactory>)factory
                         withInt:(jint)version_ {
  SquiDBSQLiteOpenHelper_initWithNSString_withNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_(self, path, name, factory, version_);
  return self;
}

- (instancetype)initWithNSString:(NSString *)path
                    withNSString:(NSString *)name
withSquiDBSQLiteDatabase_CursorFactory:(id<SquiDBSQLiteDatabase_CursorFactory>)factory
                         withInt:(jint)version_
  withSquiDBDatabaseErrorHandler:(id<SquiDBDatabaseErrorHandler>)errorHandler {
  SquiDBSQLiteOpenHelper_initWithNSString_withNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_withSquiDBDatabaseErrorHandler_(self, path, name, factory, version_, errorHandler);
  return self;
}

- (JavaIoFile *)getDatabaseFile {
  return mDatabasePath_;
}

- (NSString *)getDatabaseName {
  return mName_;
}

- (void)setWriteAheadLoggingEnabledWithBoolean:(jboolean)enabled {
  @synchronized(self) {
    if (mEnableWriteAheadLogging_ != enabled) {
      if (mDatabase_ != nil && [mDatabase_ isOpen] && ![((SquiDBSQLiteDatabase *) nil_chk(mDatabase_)) isReadOnly]) {
        if (enabled) {
          [mDatabase_ enableWriteAheadLogging];
        }
        else {
          [mDatabase_ disableWriteAheadLogging];
        }
      }
      mEnableWriteAheadLogging_ = enabled;
    }
  }
}

- (SquiDBSQLiteDatabase *)getWritableDatabase {
  @synchronized(self) {
    return SquiDBSQLiteOpenHelper_getDatabaseLockedWithBoolean_(self, true);
  }
}

- (SquiDBSQLiteDatabase *)getReadableDatabase {
  @synchronized(self) {
    return SquiDBSQLiteOpenHelper_getDatabaseLockedWithBoolean_(self, false);
  }
}

- (SquiDBSQLiteDatabase *)getDatabaseLockedWithBoolean:(jboolean)writable {
  return SquiDBSQLiteOpenHelper_getDatabaseLockedWithBoolean_(self, writable);
}

- (void)close {
  @synchronized(self) {
    if (mIsInitializing_) {
      @throw new_JavaLangIllegalStateException_initWithNSString_(@"Closed during initialization");
    }
    if (mDatabase_ != nil && [mDatabase_ isOpen]) {
      [mDatabase_ close];
      mDatabase_ = nil;
    }
  }
}

- (void)onConfigureWithSquiDBSQLiteDatabase:(SquiDBSQLiteDatabase *)db {
}

- (void)onCreateWithSquiDBSQLiteDatabase:(SquiDBSQLiteDatabase *)db {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)onUpgradeWithSquiDBSQLiteDatabase:(SquiDBSQLiteDatabase *)db
                                  withInt:(jint)oldVersion
                                  withInt:(jint)newVersion {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)onDowngradeWithSquiDBSQLiteDatabase:(SquiDBSQLiteDatabase *)db
                                    withInt:(jint)oldVersion
                                    withInt:(jint)newVersion {
  @throw new_SquiDBSQLiteException_initWithNSString_(JreStrcat("$I$I", @"Can't downgrade database from version ", oldVersion, @" to ", newVersion));
}

- (void)onOpenWithSquiDBSQLiteDatabase:(SquiDBSQLiteDatabase *)db {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "LJavaIoFile;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LSquiDBSQLiteDatabase;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LSquiDBSQLiteDatabase;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LSquiDBSQLiteDatabase;", 0x2, 4, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x21, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 7, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 11, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:withNSString:withSquiDBSQLiteDatabase_CursorFactory:withInt:);
  methods[1].selector = @selector(initWithNSString:withNSString:withSquiDBSQLiteDatabase_CursorFactory:withInt:withSquiDBDatabaseErrorHandler:);
  methods[2].selector = @selector(getDatabaseFile);
  methods[3].selector = @selector(getDatabaseName);
  methods[4].selector = @selector(setWriteAheadLoggingEnabledWithBoolean:);
  methods[5].selector = @selector(getWritableDatabase);
  methods[6].selector = @selector(getReadableDatabase);
  methods[7].selector = @selector(getDatabaseLockedWithBoolean:);
  methods[8].selector = @selector(close);
  methods[9].selector = @selector(onConfigureWithSquiDBSQLiteDatabase:);
  methods[10].selector = @selector(onCreateWithSquiDBSQLiteDatabase:);
  methods[11].selector = @selector(onUpgradeWithSquiDBSQLiteDatabase:withInt:withInt:);
  methods[12].selector = @selector(onDowngradeWithSquiDBSQLiteDatabase:withInt:withInt:);
  methods[13].selector = @selector(onOpenWithSquiDBSQLiteDatabase:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TAG", "LNSString;", .constantValue.asLong = 0, 0x1a, -1, 12, -1, -1 },
    { "DEBUG_STRICT_READONLY", "Z", .constantValue.asBOOL = SquiDBSQLiteOpenHelper_DEBUG_STRICT_READONLY, 0x1a, -1, -1, -1, -1 },
    { "mPath_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mName_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mDatabasePath_", "LJavaIoFile;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mFactory_", "LSquiDBSQLiteDatabase_CursorFactory;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mNewVersion_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "mDatabase_", "LSquiDBSQLiteDatabase;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mIsInitializing_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mEnableWriteAheadLogging_", "Z", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mErrorHandler_", "LSquiDBDatabaseErrorHandler;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LNSString;LSquiDBSQLiteDatabase_CursorFactory;I", "LNSString;LNSString;LSquiDBSQLiteDatabase_CursorFactory;ILSquiDBDatabaseErrorHandler;", "setWriteAheadLoggingEnabled", "Z", "getDatabaseLocked", "onConfigure", "LSquiDBSQLiteDatabase;", "onCreate", "onUpgrade", "LSquiDBSQLiteDatabase;II", "onDowngrade", "onOpen", &SquiDBSQLiteOpenHelper_TAG };
  static const J2ObjcClassInfo _SquiDBSQLiteOpenHelper = { "SQLiteOpenHelper", "com.yahoo.android.sqlite", ptrTable, methods, fields, 7, 0x401, 14, 11, -1, -1, -1, -1, -1 };
  return &_SquiDBSQLiteOpenHelper;
}

+ (void)initialize {
  if (self == [SquiDBSQLiteOpenHelper class]) {
    SquiDBSQLiteOpenHelper_TAG = [SquiDBSQLiteOpenHelper_class_() getSimpleName];
    J2OBJC_SET_INITIALIZED(SquiDBSQLiteOpenHelper)
  }
}

@end

void SquiDBSQLiteOpenHelper_initWithNSString_withNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_(SquiDBSQLiteOpenHelper *self, NSString *path, NSString *name, id<SquiDBSQLiteDatabase_CursorFactory> factory, jint version_) {
  SquiDBSQLiteOpenHelper_initWithNSString_withNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_withSquiDBDatabaseErrorHandler_(self, path, name, factory, version_, nil);
}

void SquiDBSQLiteOpenHelper_initWithNSString_withNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_withSquiDBDatabaseErrorHandler_(SquiDBSQLiteOpenHelper *self, NSString *path, NSString *name, id<SquiDBSQLiteDatabase_CursorFactory> factory, jint version_, id<SquiDBDatabaseErrorHandler> errorHandler) {
  NSObject_init(self);
  if (version_ < 1) {
    @throw new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$I", @"Version must be >= 1, was ", version_));
  }
  self->mPath_ = path;
  self->mName_ = name;
  self->mDatabasePath_ = new_JavaIoFile_initWithNSString_withNSString_(path, name);
  self->mFactory_ = factory;
  self->mNewVersion_ = version_;
  self->mErrorHandler_ = errorHandler;
}

SquiDBSQLiteDatabase *SquiDBSQLiteOpenHelper_getDatabaseLockedWithBoolean_(SquiDBSQLiteOpenHelper *self, jboolean writable) {
  if (self->mDatabase_ != nil) {
    if (![self->mDatabase_ isOpen]) {
      self->mDatabase_ = nil;
    }
    else if (!writable || ![((SquiDBSQLiteDatabase *) nil_chk(self->mDatabase_)) isReadOnly]) {
      return self->mDatabase_;
    }
  }
  if (self->mIsInitializing_) {
    @throw new_JavaLangIllegalStateException_initWithNSString_(@"getDatabase called recursively");
  }
  SquiDBSQLiteDatabase *db = self->mDatabase_;
  @try {
    self->mIsInitializing_ = true;
    if (db != nil) {
      if (writable && [db isReadOnly]) {
        [db reopenReadWrite];
      }
    }
    else if (self->mName_ == nil) {
      db = SquiDBSQLiteDatabase_createWithSquiDBSQLiteDatabase_CursorFactory_(nil);
    }
    else {
      @try {
        {
          JavaIoFile *databasePath = self->mDatabasePath_;
          JavaIoFile *databaseParent = [((JavaIoFile *) nil_chk(databasePath)) getParentFile];
          if ([((JavaIoFile *) nil_chk(databaseParent)) mkdirs] || [databaseParent isDirectory]) {
            NSString *path = [databasePath getPath];
            db = SquiDBSQLiteDatabase_openOrCreateDatabaseWithNSString_withSquiDBSQLiteDatabase_CursorFactory_withSquiDBDatabaseErrorHandler_(path, self->mFactory_, self->mErrorHandler_);
          }
          else {
            @throw new_SquiDBSQLiteCantOpenDatabaseException_initWithNSString_(@"Failed to create database parent directory");
          }
        }
      }
      @catch (SquiDBSQLiteException *ex) {
        if (writable) {
          @throw ex;
        }
        SquiDBLogger_eWithNSString_withNSString_withJavaLangThrowable_(SquiDBSQLiteOpenHelper_TAG, JreStrcat("$$$", @"Couldn't open ", self->mName_, @" for writing (will try read-only):"), ex);
        NSString *path = [((JavaIoFile *) nil_chk(self->mDatabasePath_)) getPath];
        db = SquiDBSQLiteDatabase_openDatabaseWithNSString_withSquiDBSQLiteDatabase_CursorFactory_withInt_withSquiDBDatabaseErrorHandler_(path, self->mFactory_, SquiDBSQLiteDatabase_OPEN_READONLY, self->mErrorHandler_);
      }
    }
    [self onConfigureWithSquiDBSQLiteDatabase:db];
    jint version_ = [((SquiDBSQLiteDatabase *) nil_chk(db)) getVersion];
    if (version_ != self->mNewVersion_) {
      if ([db isReadOnly]) {
        @throw new_SquiDBSQLiteException_initWithNSString_(JreStrcat("$I$I$$", @"Can't upgrade read-only database from version ", [db getVersion], @" to ", self->mNewVersion_, @": ", self->mName_));
      }
      [db beginTransaction];
      @try {
        if (version_ == 0) {
          [self onCreateWithSquiDBSQLiteDatabase:db];
        }
        else {
          if (version_ > self->mNewVersion_) {
            [self onDowngradeWithSquiDBSQLiteDatabase:db withInt:version_ withInt:self->mNewVersion_];
          }
          else {
            [self onUpgradeWithSquiDBSQLiteDatabase:db withInt:version_ withInt:self->mNewVersion_];
          }
        }
        [db setVersionWithInt:self->mNewVersion_];
        [db setTransactionSuccessful];
      }
      @finally {
        [db endTransaction];
      }
    }
    [self onOpenWithSquiDBSQLiteDatabase:db];
    if ([db isReadOnly]) {
      SquiDBLogger_wWithNSString_withNSString_(SquiDBSQLiteOpenHelper_TAG, JreStrcat("$$$", @"Opened ", self->mName_, @" in read-only mode"));
    }
    self->mDatabase_ = db;
    return db;
  }
  @finally {
    self->mIsInitializing_ = false;
    if (db != nil && db != self->mDatabase_) {
      [db close];
    }
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SquiDBSQLiteOpenHelper)

J2OBJC_NAME_MAPPING(SquiDBSQLiteOpenHelper, "com.yahoo.android.sqlite", "SquiDB")
