//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteAccessPermException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SQLiteAccessPermException")
#ifdef RESTRICT_SQLiteAccessPermException
#define INCLUDE_ALL_SQLiteAccessPermException 0
#else
#define INCLUDE_ALL_SQLiteAccessPermException 1
#endif
#undef RESTRICT_SQLiteAccessPermException

#if !defined (ComYahooAndroidSqliteSQLiteAccessPermException_) && (INCLUDE_ALL_SQLiteAccessPermException || defined(INCLUDE_ComYahooAndroidSqliteSQLiteAccessPermException))
#define ComYahooAndroidSqliteSQLiteAccessPermException_

#define RESTRICT_SQLiteException 1
#define INCLUDE_ComYahooAndroidSqliteSQLiteException 1
#include "SQLiteException.h"

@class JavaLangThrowable;

@interface ComYahooAndroidSqliteSQLiteAccessPermException : ComYahooAndroidSqliteSQLiteException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)error;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteSQLiteAccessPermException)

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteAccessPermException_init(ComYahooAndroidSqliteSQLiteAccessPermException *self);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAccessPermException *new_ComYahooAndroidSqliteSQLiteAccessPermException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAccessPermException *create_ComYahooAndroidSqliteSQLiteAccessPermException_init(void);

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteAccessPermException_initWithNSString_(ComYahooAndroidSqliteSQLiteAccessPermException *self, NSString *error);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAccessPermException *new_ComYahooAndroidSqliteSQLiteAccessPermException_initWithNSString_(NSString *error) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAccessPermException *create_ComYahooAndroidSqliteSQLiteAccessPermException_initWithNSString_(NSString *error);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteSQLiteAccessPermException)

#endif

#pragma pop_macro("INCLUDE_ALL_SQLiteAccessPermException")
