//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteAbortException.java
//

#ifndef SQLiteAbortException_H
#define SQLiteAbortException_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "SQLiteException.h"

@class JavaLangThrowable;

@interface ComYahooAndroidSqliteSQLiteAbortException : ComYahooAndroidSqliteSQLiteException

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithNSString:(NSString *)error;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteSQLiteAbortException)

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteAbortException_init(ComYahooAndroidSqliteSQLiteAbortException *self);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAbortException *new_ComYahooAndroidSqliteSQLiteAbortException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAbortException *create_ComYahooAndroidSqliteSQLiteAbortException_init(void);

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(ComYahooAndroidSqliteSQLiteAbortException *self, NSString *error);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAbortException *new_ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(NSString *error) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteAbortException *create_ComYahooAndroidSqliteSQLiteAbortException_initWithNSString_(NSString *error);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteSQLiteAbortException)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // SQLiteAbortException_H
