//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteBlobTooBigException.java
//

#ifndef SQLiteBlobTooBigException_H
#define SQLiteBlobTooBigException_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "SQLiteException.h"

@class JavaLangThrowable;

@interface ComYahooAndroidSqliteSQLiteBlobTooBigException : ComYahooAndroidSqliteSQLiteException

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithNSString:(NSString *)error;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithNSString:(NSString *)arg0
                     withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteSQLiteBlobTooBigException)

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteBlobTooBigException_init(ComYahooAndroidSqliteSQLiteBlobTooBigException *self);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteBlobTooBigException *new_ComYahooAndroidSqliteSQLiteBlobTooBigException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteBlobTooBigException *create_ComYahooAndroidSqliteSQLiteBlobTooBigException_init(void);

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteBlobTooBigException_initWithNSString_(ComYahooAndroidSqliteSQLiteBlobTooBigException *self, NSString *error);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteBlobTooBigException *new_ComYahooAndroidSqliteSQLiteBlobTooBigException_initWithNSString_(NSString *error) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteBlobTooBigException *create_ComYahooAndroidSqliteSQLiteBlobTooBigException_initWithNSString_(NSString *error);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteSQLiteBlobTooBigException)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // SQLiteBlobTooBigException_H
