//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteDatabaseLockedException.java
//

#include "J2ObjC_source.h"
#include "SQLiteDatabaseLockedException.h"
#include "SQLiteException.h"

@implementation ComYahooAndroidSqliteSQLiteDatabaseLockedException

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComYahooAndroidSqliteSQLiteDatabaseLockedException_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)error {
  ComYahooAndroidSqliteSQLiteDatabaseLockedException_initWithNSString_(self, error);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _ComYahooAndroidSqliteSQLiteDatabaseLockedException = { "SQLiteDatabaseLockedException", "com.yahoo.android.sqlite", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComYahooAndroidSqliteSQLiteDatabaseLockedException;
}

@end

void ComYahooAndroidSqliteSQLiteDatabaseLockedException_init(ComYahooAndroidSqliteSQLiteDatabaseLockedException *self) {
  ComYahooAndroidSqliteSQLiteException_init(self);
}

ComYahooAndroidSqliteSQLiteDatabaseLockedException *new_ComYahooAndroidSqliteSQLiteDatabaseLockedException_init() {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteDatabaseLockedException, init)
}

ComYahooAndroidSqliteSQLiteDatabaseLockedException *create_ComYahooAndroidSqliteSQLiteDatabaseLockedException_init() {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteDatabaseLockedException, init)
}

void ComYahooAndroidSqliteSQLiteDatabaseLockedException_initWithNSString_(ComYahooAndroidSqliteSQLiteDatabaseLockedException *self, NSString *error) {
  ComYahooAndroidSqliteSQLiteException_initWithNSString_(self, error);
}

ComYahooAndroidSqliteSQLiteDatabaseLockedException *new_ComYahooAndroidSqliteSQLiteDatabaseLockedException_initWithNSString_(NSString *error) {
  J2OBJC_NEW_IMPL(ComYahooAndroidSqliteSQLiteDatabaseLockedException, initWithNSString_, error)
}

ComYahooAndroidSqliteSQLiteDatabaseLockedException *create_ComYahooAndroidSqliteSQLiteDatabaseLockedException_initWithNSString_(NSString *error) {
  J2OBJC_CREATE_IMPL(ComYahooAndroidSqliteSQLiteDatabaseLockedException, initWithNSString_, error)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooAndroidSqliteSQLiteDatabaseLockedException)
