//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SqlTable.java
//

#ifndef SqlTable_H
#define SqlTable_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "DBObject.h"
#include "J2ObjC_header.h"

@class IOSClass;
@class IOSObjectArray;
@class SquiDBField;
@protocol JavaUtilList;

@interface SquiDBSqlTable : SquiDBDBObject {
 @public
  IOSClass *modelClass_;
  IOSObjectArray *properties_;
}

#pragma mark Public

- (SquiDBSqlTable *)asWithNSString:(NSString *)newAlias;

- (IOSClass *)getModelClass;

- (IOSObjectArray *)getProperties;

- (SquiDBField *)qualifyFieldWithSquiDBField:(SquiDBField *)field;

- (IOSObjectArray *)qualifyFieldsWithSquiDBFieldArray:(IOSObjectArray *)fields;

- (IOSObjectArray *)qualifyFieldsWithJavaUtilList:(id<JavaUtilList>)fields;

#pragma mark Protected

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)modelClass
                   withSquiDBPropertyArray:(IOSObjectArray *)properties
                              withNSString:(NSString *)expression;

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)modelClass
                   withSquiDBPropertyArray:(IOSObjectArray *)properties
                              withNSString:(NSString *)expression
                              withNSString:(NSString *)qualifier;

- (IOSObjectArray *)allFields;

- (SquiDBSqlTable *)asNewAliasWithPropertiesArrayWithNSString:(NSString *)newAlias
                                      withSquiDBPropertyArray:(IOSObjectArray *)newProperties;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initPackagePrivateWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype __nonnull)initPackagePrivateWithNSString:(NSString *)arg0
                                            withNSString:(NSString *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SquiDBSqlTable)

J2OBJC_FIELD_SETTER(SquiDBSqlTable, modelClass_, IOSClass *)
J2OBJC_FIELD_SETTER(SquiDBSqlTable, properties_, IOSObjectArray *)

FOUNDATION_EXPORT void SquiDBSqlTable_initWithIOSClass_withSquiDBPropertyArray_withNSString_(SquiDBSqlTable *self, IOSClass *modelClass, IOSObjectArray *properties, NSString *expression);

FOUNDATION_EXPORT void SquiDBSqlTable_initWithIOSClass_withSquiDBPropertyArray_withNSString_withNSString_(SquiDBSqlTable *self, IOSClass *modelClass, IOSObjectArray *properties, NSString *expression, NSString *qualifier);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBSqlTable)

@compatibility_alias ComYahooSquidbSqlSqlTable SquiDBSqlTable;


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // SqlTable_H
