//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SquidCursorFactory.java
//

#include "DatabaseUtils.h"
#include "ICursor.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "SQLiteCursor.h"
#include "SQLiteCursorDriver.h"
#include "SQLiteDatabase.h"
#include "SQLiteProgram.h"
#include "SQLiteQuery.h"
#include "SquidCursorFactory.h"

@interface ComYahooSquidbIosSquidCursorFactory () {
 @public
  IOSObjectArray *sqlArgs_;
}

@end

J2OBJC_FIELD_SETTER(ComYahooSquidbIosSquidCursorFactory, sqlArgs_, IOSObjectArray *)

@implementation ComYahooSquidbIosSquidCursorFactory

- (instancetype)initWithNSObjectArray:(IOSObjectArray *)sqlArgs {
  ComYahooSquidbIosSquidCursorFactory_initWithNSObjectArray_(self, sqlArgs);
  return self;
}

- (id<ComYahooSquidbDataICursor>)newCursorWithComYahooAndroidSqliteSQLiteDatabase:(ComYahooAndroidSqliteSQLiteDatabase *)db
                                      withComYahooAndroidSqliteSQLiteCursorDriver:(id<ComYahooAndroidSqliteSQLiteCursorDriver>)masterQuery
                                                                     withNSString:(NSString *)editTable
                                             withComYahooAndroidSqliteSQLiteQuery:(ComYahooAndroidSqliteSQLiteQuery *)query {
  ComYahooSquidbIosSquidCursorFactory_bindArgumentsToProgramWithComYahooAndroidSqliteSQLiteProgram_withNSObjectArray_(query, sqlArgs_);
  return new_ComYahooAndroidSqliteSQLiteCursor_initWithComYahooAndroidSqliteSQLiteCursorDriver_withNSString_withComYahooAndroidSqliteSQLiteQuery_(masterQuery, editTable, query);
}

+ (void)bindArgumentsToProgramWithComYahooAndroidSqliteSQLiteProgram:(ComYahooAndroidSqliteSQLiteProgram *)program
                                                   withNSObjectArray:(IOSObjectArray *)sqlArgs {
  ComYahooSquidbIosSquidCursorFactory_bindArgumentsToProgramWithComYahooAndroidSqliteSQLiteProgram_withNSObjectArray_(program, sqlArgs);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LComYahooSquidbDataICursor;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSObjectArray:);
  methods[1].selector = @selector(newCursorWithComYahooAndroidSqliteSQLiteDatabase:withComYahooAndroidSqliteSQLiteCursorDriver:withNSString:withComYahooAndroidSqliteSQLiteQuery:);
  methods[2].selector = @selector(bindArgumentsToProgramWithComYahooAndroidSqliteSQLiteProgram:withNSObjectArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "sqlArgs_", "[LNSObject;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "[LNSObject;", "newCursor", "LComYahooAndroidSqliteSQLiteDatabase;LComYahooAndroidSqliteSQLiteCursorDriver;LNSString;LComYahooAndroidSqliteSQLiteQuery;", "bindArgumentsToProgram", "LComYahooAndroidSqliteSQLiteProgram;[LNSObject;" };
  static const J2ObjcClassInfo _ComYahooSquidbIosSquidCursorFactory = { "SquidCursorFactory", "com.yahoo.squidb.ios", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, -1, -1 };
  return &_ComYahooSquidbIosSquidCursorFactory;
}

@end

void ComYahooSquidbIosSquidCursorFactory_initWithNSObjectArray_(ComYahooSquidbIosSquidCursorFactory *self, IOSObjectArray *sqlArgs) {
  NSObject_init(self);
  self->sqlArgs_ = sqlArgs;
}

ComYahooSquidbIosSquidCursorFactory *new_ComYahooSquidbIosSquidCursorFactory_initWithNSObjectArray_(IOSObjectArray *sqlArgs) {
  J2OBJC_NEW_IMPL(ComYahooSquidbIosSquidCursorFactory, initWithNSObjectArray_, sqlArgs)
}

ComYahooSquidbIosSquidCursorFactory *create_ComYahooSquidbIosSquidCursorFactory_initWithNSObjectArray_(IOSObjectArray *sqlArgs) {
  J2OBJC_CREATE_IMPL(ComYahooSquidbIosSquidCursorFactory, initWithNSObjectArray_, sqlArgs)
}

void ComYahooSquidbIosSquidCursorFactory_bindArgumentsToProgramWithComYahooAndroidSqliteSQLiteProgram_withNSObjectArray_(ComYahooAndroidSqliteSQLiteProgram *program, IOSObjectArray *sqlArgs) {
  ComYahooSquidbIosSquidCursorFactory_initialize();
  if (sqlArgs == nil) {
    return;
  }
  for (jint i = 1; i <= sqlArgs->size_; i++) {
    ComYahooAndroidSqliteDatabaseUtils_bindObjectToProgramWithComYahooAndroidSqliteSQLiteProgram_withInt_withId_(program, i, IOSObjectArray_Get(sqlArgs, i - 1));
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComYahooSquidbIosSquidCursorFactory)
