//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SquidUtilities.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SquidUtilities")
#ifdef RESTRICT_SquidUtilities
#define INCLUDE_ALL_SquidUtilities 0
#else
#define INCLUDE_ALL_SquidUtilities 1
#endif
#undef RESTRICT_SquidUtilities

#if !defined (ComYahooSquidbUtilitySquidUtilities_) && (INCLUDE_ALL_SquidUtilities || defined(INCLUDE_ComYahooSquidbUtilitySquidUtilities))
#define ComYahooSquidbUtilitySquidUtilities_

@class ComYahooSquidbDataSquidDatabase;
@class IOSObjectArray;
@class JavaIoFile;
@class JavaLangStringBuilder;
@protocol ComYahooSquidbDataICursor;
@protocol JavaUtilCollection;

@interface ComYahooSquidbUtilitySquidUtilities : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)addAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection
                   withNSObjectArray:(IOSObjectArray *)objects;

+ (void)copyDatabaseWithComYahooSquidbDataSquidDatabase:(ComYahooSquidbDataSquidDatabase *)database
                                           withNSString:(NSString *)toFolder OBJC_METHOD_FAMILY_NONE;

+ (void)copyFileWithJavaIoFile:(JavaIoFile *)inArg
                withJavaIoFile:(JavaIoFile *)outArg OBJC_METHOD_FAMILY_NONE;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                            withInt:(jint)maxColumnWidth;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                            withInt:(jint)maxColumnWidth
                          withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCurrentRowWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                          withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                        withInt:(jint)maxColumnWidth;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                                        withInt:(jint)maxColumnWidth
                      withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

+ (void)dumpCursorWithComYahooSquidbDataICursor:(id<ComYahooSquidbDataICursor>)cursor
                      withJavaLangStringBuilder:(JavaLangStringBuilder *)builder;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbUtilitySquidUtilities)

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_init(ComYahooSquidbUtilitySquidUtilities *self);

FOUNDATION_EXPORT ComYahooSquidbUtilitySquidUtilities *new_ComYahooSquidbUtilitySquidUtilities_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbUtilitySquidUtilities *create_ComYahooSquidbUtilitySquidUtilities_init(void);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_(id<ComYahooSquidbDataICursor> cursor);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withInt_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCursorWithComYahooSquidbDataICursor_withInt_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_(id<ComYahooSquidbDataICursor> cursor);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withInt_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_dumpCurrentRowWithComYahooSquidbDataICursor_withInt_withJavaLangStringBuilder_(id<ComYahooSquidbDataICursor> cursor, jint maxColumnWidth, JavaLangStringBuilder *builder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_addAllWithJavaUtilCollection_withNSObjectArray_(id<JavaUtilCollection> collection, IOSObjectArray *objects);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_copyDatabaseWithComYahooSquidbDataSquidDatabase_withNSString_(ComYahooSquidbDataSquidDatabase *database, NSString *toFolder);

FOUNDATION_EXPORT void ComYahooSquidbUtilitySquidUtilities_copyFileWithJavaIoFile_withJavaIoFile_(JavaIoFile *inArg, JavaIoFile *outArg);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbUtilitySquidUtilities)

#endif

#pragma pop_macro("INCLUDE_ALL_SquidUtilities")
