//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/TableModelName.java
//

#ifndef TableModelName_H
#define TableModelName_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"

@class IOSClass;

@interface ComYahooSquidbSqlTableModelName : NSObject {
 @public
  IOSClass *modelClass_;
  NSString *tableName_;
}

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)modelClass
                              withNSString:(NSString *)tableName;

- (jboolean)isEqual:(id)o;

- (NSUInteger)hash;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbSqlTableModelName)

J2OBJC_FIELD_SETTER(ComYahooSquidbSqlTableModelName, modelClass_, IOSClass *)
J2OBJC_FIELD_SETTER(ComYahooSquidbSqlTableModelName, tableName_, NSString *)

FOUNDATION_EXPORT void ComYahooSquidbSqlTableModelName_initWithIOSClass_withNSString_(ComYahooSquidbSqlTableModelName *self, IOSClass *modelClass, NSString *tableName);

FOUNDATION_EXPORT ComYahooSquidbSqlTableModelName *new_ComYahooSquidbSqlTableModelName_initWithIOSClass_withNSString_(IOSClass *modelClass, NSString *tableName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlTableModelName *create_ComYahooSquidbSqlTableModelName_initWithIOSClass_withNSString_(IOSClass *modelClass, NSString *tableName);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlTableModelName)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // TableModelName_H
