//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/VersionCode.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_VersionCode")
#ifdef RESTRICT_VersionCode
#define INCLUDE_ALL_VersionCode 0
#else
#define INCLUDE_ALL_VersionCode 1
#endif
#undef RESTRICT_VersionCode

#if !defined (ComYahooSquidbUtilityVersionCode_) && (INCLUDE_ALL_VersionCode || defined(INCLUDE_ComYahooSquidbUtilityVersionCode))
#define ComYahooSquidbUtilityVersionCode_

#define RESTRICT_JavaLangComparable 1
#define INCLUDE_JavaLangComparable 1
#include "java/lang/Comparable.h"

@interface ComYahooSquidbUtilityVersionCode : NSObject < JavaLangComparable >

+ (ComYahooSquidbUtilityVersionCode *)V3_7_4;

+ (ComYahooSquidbUtilityVersionCode *)V3_7_11;

+ (ComYahooSquidbUtilityVersionCode *)V3_8_3;

+ (ComYahooSquidbUtilityVersionCode *)LATEST;

#pragma mark Public

- (instancetype)initWithInt:(jint)major
                    withInt:(jint)minor
                    withInt:(jint)micro
                    withInt:(jint)nano;

- (instancetype)initWithInt:(jint)major
                    withInt:(jint)minor
                    withInt:(jint)micro
                    withInt:(jint)nano
               withNSString:(NSString *)trailing;

- (jint)compareToWithId:(ComYahooSquidbUtilityVersionCode *)other;

- (jboolean)isEqual:(id)o;

- (jint)getMajorVersion;

- (jint)getMicroVersion;

- (jint)getMinorVersion;

- (jint)getNanoVersion;

- (NSString *)getTrailingText;

- (NSUInteger)hash;

- (jboolean)isAtLeastWithNSString:(NSString *)versionString;

- (jboolean)isAtLeastWithComYahooSquidbUtilityVersionCode:(ComYahooSquidbUtilityVersionCode *)version_;

- (jboolean)isLessThanWithNSString:(NSString *)versionString;

- (jboolean)isLessThanWithComYahooSquidbUtilityVersionCode:(ComYahooSquidbUtilityVersionCode *)version_;

+ (ComYahooSquidbUtilityVersionCode *)parseWithNSString:(NSString *)versionString;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComYahooSquidbUtilityVersionCode)

inline ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_get_V3_7_4(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_V3_7_4;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComYahooSquidbUtilityVersionCode, V3_7_4, ComYahooSquidbUtilityVersionCode *)

inline ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_get_V3_7_11(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_V3_7_11;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComYahooSquidbUtilityVersionCode, V3_7_11, ComYahooSquidbUtilityVersionCode *)

inline ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_get_V3_8_3(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_V3_8_3;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComYahooSquidbUtilityVersionCode, V3_8_3, ComYahooSquidbUtilityVersionCode *)

inline ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_get_LATEST(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_LATEST;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComYahooSquidbUtilityVersionCode, LATEST, ComYahooSquidbUtilityVersionCode *)

FOUNDATION_EXPORT void ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_(ComYahooSquidbUtilityVersionCode *self, jint major, jint minor, jint micro, jint nano);

FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *new_ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_(jint major, jint minor, jint micro, jint nano) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *create_ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_(jint major, jint minor, jint micro, jint nano);

FOUNDATION_EXPORT void ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_withNSString_(ComYahooSquidbUtilityVersionCode *self, jint major, jint minor, jint micro, jint nano, NSString *trailing);

FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *new_ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_withNSString_(jint major, jint minor, jint micro, jint nano, NSString *trailing) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *create_ComYahooSquidbUtilityVersionCode_initWithInt_withInt_withInt_withInt_withNSString_(jint major, jint minor, jint micro, jint nano, NSString *trailing);

FOUNDATION_EXPORT ComYahooSquidbUtilityVersionCode *ComYahooSquidbUtilityVersionCode_parseWithNSString_(NSString *versionString);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbUtilityVersionCode)

#endif

#pragma pop_macro("INCLUDE_ALL_VersionCode")
