//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ViewQuery.java
//

#ifndef ViewQuery_H
#define ViewQuery_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol SquiDBViewQuery < JavaLangAnnotationAnnotation >

@property (readonly) jboolean freeze;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface SquiDBViewQuery : NSObject < SquiDBViewQuery > {
 @public
  jboolean freeze_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(SquiDBViewQuery)

FOUNDATION_EXPORT id<SquiDBViewQuery> create_SquiDBViewQuery(jboolean freeze);

J2OBJC_TYPE_LITERAL_HEADER(SquiDBViewQuery)

#define ComYahooSquidbAnnotationsViewQuery SquiDBViewQuery


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // ViewQuery_H
