//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/ViewModelSpec.java
//

#ifndef ViewModelSpec_H
#define ViewModelSpec_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol ComYahooSquidbAnnotationsViewModelSpec < JavaLangAnnotationAnnotation >

@property (readonly) NSString *className__;
@property (readonly) NSString *viewName;
@property (readonly) jboolean isSubquery;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComYahooSquidbAnnotationsViewModelSpec : NSObject < ComYahooSquidbAnnotationsViewModelSpec > {
 @public
  NSString *className___;
  NSString *viewName_;
  jboolean isSubquery_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbAnnotationsViewModelSpec)

FOUNDATION_EXPORT id<ComYahooSquidbAnnotationsViewModelSpec> create_ComYahooSquidbAnnotationsViewModelSpec(NSString *className__, jboolean isSubquery, NSString *viewName);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbAnnotationsViewModelSpec)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // ViewModelSpec_H
