//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/VirtualTable.java
//

#ifndef VirtualTable_H
#define VirtualTable_H

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#include "J2ObjC_header.h"
#include "Table.h"

@class ComYahooSquidbSqlCompileContext;
@class ComYahooSquidbSqlCriterion;
@class IOSClass;
@class IOSObjectArray;
@class JavaLangStringBuilder;
@protocol ComYahooSquidbSqlProperty_PropertyVisitor;

@interface ComYahooSquidbSqlVirtualTable : ComYahooSquidbSqlTable

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)modelClass
        withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)properties
                              withNSString:(NSString *)name
                              withNSString:(NSString *)databaseName
                              withNSString:(NSString *)module;

- (void)appendCreateTableSqlWithComYahooSquidbSqlCompileContext:(ComYahooSquidbSqlCompileContext *)compileContext
                                      withJavaLangStringBuilder:(JavaLangStringBuilder *)sql
                  withComYahooSquidbSqlProperty_PropertyVisitor:(id<ComYahooSquidbSqlProperty_PropertyVisitor>)propertyVisitor;

- (ComYahooSquidbSqlVirtualTable *)asWithNSString:(NSString *)newAlias;

- (NSString *)getModuleName;

- (ComYahooSquidbSqlCriterion *)matchWithNSString:(NSString *)value;

- (ComYahooSquidbSqlVirtualTable *)qualifiedFromDatabaseWithNSString:(NSString *)databaseName;

- (NSString *)description;

#pragma mark Protected

- (ComYahooSquidbSqlVirtualTable *)asNewAliasWithPropertiesArrayWithNSString:(NSString *)newAlias
                                          withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)newProperties;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)arg0
        withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)arg1
                              withNSString:(NSString *)arg2 NS_UNAVAILABLE;

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)arg0
        withComYahooSquidbSqlPropertyArray:(IOSObjectArray *)arg1
                              withNSString:(NSString *)arg2
                              withNSString:(NSString *)arg3 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComYahooSquidbSqlVirtualTable)

FOUNDATION_EXPORT void ComYahooSquidbSqlVirtualTable_initWithIOSClass_withComYahooSquidbSqlPropertyArray_withNSString_withNSString_withNSString_(ComYahooSquidbSqlVirtualTable *self, IOSClass *modelClass, IOSObjectArray *properties, NSString *name, NSString *databaseName, NSString *module);

FOUNDATION_EXPORT ComYahooSquidbSqlVirtualTable *new_ComYahooSquidbSqlVirtualTable_initWithIOSClass_withComYahooSquidbSqlPropertyArray_withNSString_withNSString_withNSString_(IOSClass *modelClass, IOSObjectArray *properties, NSString *name, NSString *databaseName, NSString *module) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooSquidbSqlVirtualTable *create_ComYahooSquidbSqlVirtualTable_initWithIOSClass_withComYahooSquidbSqlPropertyArray_withNSString_withNSString_withNSString_(IOSClass *modelClass, IOSObjectArray *properties, NSString *name, NSString *databaseName, NSString *module);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbSqlVirtualTable)


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#endif // VirtualTable_H
