//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/Alias.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Alias")
#ifdef RESTRICT_Alias
#define INCLUDE_ALL_Alias 0
#else
#define INCLUDE_ALL_Alias 1
#endif
#undef RESTRICT_Alias

#if !defined (ComYahooSquidbAnnotationsAlias_) && (INCLUDE_ALL_Alias || defined(INCLUDE_ComYahooSquidbAnnotationsAlias))
#define ComYahooSquidbAnnotationsAlias_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol ComYahooSquidbAnnotationsAlias < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooSquidbAnnotationsAlias)

J2OBJC_TYPE_LITERAL_HEADER(ComYahooSquidbAnnotationsAlias)

#endif

#pragma pop_macro("INCLUDE_ALL_Alias")
