//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/CloseGuard.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CloseGuard")
#ifdef RESTRICT_CloseGuard
#define INCLUDE_ALL_CloseGuard 0
#else
#define INCLUDE_ALL_CloseGuard 1
#endif
#undef RESTRICT_CloseGuard

#if !defined (ComYahooAndroidSqliteCloseGuard_) && (INCLUDE_ALL_CloseGuard || defined(INCLUDE_ComYahooAndroidSqliteCloseGuard))
#define ComYahooAndroidSqliteCloseGuard_

@protocol ComYahooAndroidSqliteCloseGuard_Reporter;

@interface ComYahooAndroidSqliteCloseGuard : NSObject

#pragma mark Public

- (void)close;

+ (ComYahooAndroidSqliteCloseGuard *)get;

+ (id<ComYahooAndroidSqliteCloseGuard_Reporter>)getReporter;

- (void)openWithNSString:(NSString *)closer;

+ (void)setEnabledWithBoolean:(jboolean)enabled;

+ (void)setReporterWithComYahooAndroidSqliteCloseGuard_Reporter:(id<ComYahooAndroidSqliteCloseGuard_Reporter>)reporter;

- (void)warnIfOpen;

@end

J2OBJC_STATIC_INIT(ComYahooAndroidSqliteCloseGuard)

FOUNDATION_EXPORT ComYahooAndroidSqliteCloseGuard *ComYahooAndroidSqliteCloseGuard_get(void);

FOUNDATION_EXPORT void ComYahooAndroidSqliteCloseGuard_setEnabledWithBoolean_(jboolean enabled);

FOUNDATION_EXPORT void ComYahooAndroidSqliteCloseGuard_setReporterWithComYahooAndroidSqliteCloseGuard_Reporter_(id<ComYahooAndroidSqliteCloseGuard_Reporter> reporter);

FOUNDATION_EXPORT id<ComYahooAndroidSqliteCloseGuard_Reporter> ComYahooAndroidSqliteCloseGuard_getReporter(void);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteCloseGuard)

#endif

#if !defined (ComYahooAndroidSqliteCloseGuard_Reporter_) && (INCLUDE_ALL_CloseGuard || defined(INCLUDE_ComYahooAndroidSqliteCloseGuard_Reporter))
#define ComYahooAndroidSqliteCloseGuard_Reporter_

@class JavaLangThrowable;

@protocol ComYahooAndroidSqliteCloseGuard_Reporter < JavaObject >

- (void)reportWithNSString:(NSString *)message
     withJavaLangThrowable:(JavaLangThrowable *)allocationSite;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteCloseGuard_Reporter)

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteCloseGuard_Reporter)

#endif

#pragma pop_macro("INCLUDE_ALL_CloseGuard")
