//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/LruCache.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LruCache")
#ifdef RESTRICT_LruCache
#define INCLUDE_ALL_LruCache 0
#else
#define INCLUDE_ALL_LruCache 1
#endif
#undef RESTRICT_LruCache

#if !defined (ComYahooAndroidSqliteLruCache_) && (INCLUDE_ALL_LruCache || defined(INCLUDE_ComYahooAndroidSqliteLruCache))
#define ComYahooAndroidSqliteLruCache_

@protocol JavaUtilMap;

@interface ComYahooAndroidSqliteLruCache : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)maxSize;

- (jint)createCount;

- (void)evictAll;

- (jint)evictionCount;

- (id)getWithId:(id)key;

- (jint)hitCount;

- (jint)maxSize;

- (jint)missCount;

- (id)putWithId:(id)key
         withId:(id)value;

- (jint)putCount;

- (id)removeWithId:(id)key;

- (void)resizeWithInt:(jint)maxSize;

- (jint)size;

- (id<JavaUtilMap>)snapshot;

- (NSString *)description;

- (void)trimToSizeWithInt:(jint)maxSize;

#pragma mark Protected

- (id)createWithId:(id)key;

- (void)entryRemovedWithBoolean:(jboolean)evicted
                         withId:(id)key
                         withId:(id)oldValue
                         withId:(id)newValue;

- (jint)sizeOfWithId:(id)key
              withId:(id)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteLruCache)

FOUNDATION_EXPORT void ComYahooAndroidSqliteLruCache_initWithInt_(ComYahooAndroidSqliteLruCache *self, jint maxSize);

FOUNDATION_EXPORT ComYahooAndroidSqliteLruCache *new_ComYahooAndroidSqliteLruCache_initWithInt_(jint maxSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteLruCache *create_ComYahooAndroidSqliteLruCache_initWithInt_(jint maxSize);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteLruCache)

#endif

#pragma pop_macro("INCLUDE_ALL_LruCache")
