//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./build/j2objc/java/SQLiteReadOnlyDatabaseException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SQLiteReadOnlyDatabaseException")
#ifdef RESTRICT_SQLiteReadOnlyDatabaseException
#define INCLUDE_ALL_SQLiteReadOnlyDatabaseException 0
#else
#define INCLUDE_ALL_SQLiteReadOnlyDatabaseException 1
#endif
#undef RESTRICT_SQLiteReadOnlyDatabaseException

#if !defined (ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_) && (INCLUDE_ALL_SQLiteReadOnlyDatabaseException || defined(INCLUDE_ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException))
#define ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_

#define RESTRICT_SQLiteException 1
#define INCLUDE_ComYahooAndroidSqliteSQLiteException 1
#include "SQLiteException.h"

@class JavaLangThrowable;

@interface ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException : ComYahooAndroidSqliteSQLiteException

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)error;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException)

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_init(ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *self);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *new_ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *create_ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_init(void);

FOUNDATION_EXPORT void ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_initWithNSString_(ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *self, NSString *error);

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *new_ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_initWithNSString_(NSString *error) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException *create_ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException_initWithNSString_(NSString *error);

J2OBJC_TYPE_LITERAL_HEADER(ComYahooAndroidSqliteSQLiteReadOnlyDatabaseException)

#endif

#pragma pop_macro("INCLUDE_ALL_SQLiteReadOnlyDatabaseException")
